export enum ActionType {
    ChooseFaction = 'ChooseFaction',
    StartTurn = 'StartTurn',
    BuildShip = 'BuildShip',
    RepairShip = 'RepairShip',
    ScrapShip = 'ScrapShip',
    CloneSettlement = 'CloneSettlement',
    BuySettlements = 'BuySettlements',
    LoadSettlement = 'LoadSettlement',
    TransferSettlements = 'TransferSettlements',
    UnloadSettlements = 'UnloadSettlements',
    MoveShip = 'MoveShip',
    Explore = 'Explore',
    DevelopTech = 'DevelopTech',
    EndStep = 'EndStep',
    ResolveSurvey = 'ResolveSurvey',
    ChooseSurveyWorld = 'ChooseSurveyWorld',
    Terraform = 'Terraform',
    PassTerraform = 'PassTerraform',
    ChooseTerraformWorld = 'ChooseTerraformWorld',
    EndTurn = 'EndTurn'
}
