// Generated by `scripts/generate-image-manifests.mjs` before every build and bundle; 326 assets.
import img0 from './cards/arcane/denizen.arcane.acting-troupe.jpg'
import img1 from './cards/arcane/denizen.arcane.alchemist.jpg'
import img2 from './cards/arcane/denizen.arcane.augury.jpg'
import img3 from './cards/arcane/denizen.arcane.bewitch.jpg'
import img4 from './cards/arcane/denizen.arcane.billowing-fog.jpg'
import img5 from './cards/arcane/denizen.arcane.blood-pact.jpg'
import img6 from './cards/arcane/denizen.arcane.cracking-ground.jpg'
import img7 from './cards/arcane/denizen.arcane.dazzle.jpg'
import img8 from './cards/arcane/denizen.arcane.dream-thief.jpg'
import img9 from './cards/arcane/denizen.arcane.fire-talkers.jpg'
import img10 from './cards/arcane/denizen.arcane.forgotten-vault.jpg'
import img11 from './cards/arcane/denizen.arcane.gleaming-armor.jpg'
import img12 from './cards/arcane/denizen.arcane.initiation-rite.jpg'
import img13 from './cards/arcane/denizen.arcane.inquisitor.jpg'
import img14 from './cards/arcane/denizen.arcane.jinx.jpg'
import img15 from './cards/arcane/denizen.arcane.kindred-warriors.jpg'
import img16 from './cards/arcane/denizen.arcane.magicians-code.jpg'
import img17 from './cards/arcane/denizen.arcane.map-library.jpg'
import img18 from './cards/arcane/denizen.arcane.master-of-disguise.jpg'
import img19 from './cards/arcane/denizen.arcane.observatory.jpg'
import img20 from './cards/arcane/denizen.arcane.plague-engines.jpg'
import img21 from './cards/arcane/denizen.arcane.portal.jpg'
import img22 from './cards/arcane/denizen.arcane.revelation.jpg'
import img23 from './cards/arcane/denizen.arcane.rusting-ray.jpg'
import img24 from './cards/arcane/denizen.arcane.sealing-ward.jpg'
import img25 from './cards/arcane/denizen.arcane.secret-signal.jpg'
import img26 from './cards/arcane/denizen.arcane.spirit-snare.jpg'
import img27 from './cards/arcane/denizen.arcane.taming-charm.jpg'
import img28 from './cards/arcane/denizen.arcane.terror-spells.jpg'
import img29 from './cards/arcane/denizen.arcane.tutor.jpg'
import img30 from './cards/arcane/denizen.arcane.vow-of-silence.jpg'
import img31 from './cards/arcane/denizen.arcane.witchs-bargain.jpg'
import img32 from './cards/arcane/denizen.arcane.wizard-school.jpg'
import img33 from './cards/beast/denizen.beast.animal-host.jpg'
import img34 from './cards/beast/denizen.beast.animal-playmates.jpg'
import img35 from './cards/beast/denizen.beast.birdsong.jpg'
import img36 from './cards/beast/denizen.beast.bracken.jpg'
import img37 from './cards/beast/denizen.beast.errand-boy.jpg'
import img38 from './cards/beast/denizen.beast.fae-merchant.jpg'
import img39 from './cards/beast/denizen.beast.forest-council.jpg'
import img40 from './cards/beast/denizen.beast.forest-paths.jpg'
import img41 from './cards/beast/denizen.beast.giant-python.jpg'
import img42 from './cards/beast/denizen.beast.grasping-vines.jpg'
import img43 from './cards/beast/denizen.beast.insect-swarm.jpg'
import img44 from './cards/beast/denizen.beast.long-lost-heir.jpg'
import img45 from './cards/beast/denizen.beast.marsh-spirit.jpg'
import img46 from './cards/beast/denizen.beast.memory-of-nature.jpg'
import img47 from './cards/beast/denizen.beast.mushrooms.jpg'
import img48 from './cards/beast/denizen.beast.nature-worship.jpg'
import img49 from './cards/beast/denizen.beast.new-growth.jpg'
import img50 from './cards/beast/denizen.beast.pied-piper.jpg'
import img51 from './cards/beast/denizen.beast.rangers.jpg'
import img52 from './cards/beast/denizen.beast.roving-terror.jpg'
import img53 from './cards/beast/denizen.beast.second-chance.jpg'
import img54 from './cards/beast/denizen.beast.small-friends.jpg'
import img55 from './cards/beast/denizen.beast.the-old-oak.jpg'
import img56 from './cards/beast/denizen.beast.threatening-roar.jpg'
import img57 from './cards/beast/denizen.beast.true-names.jpg'
import img58 from './cards/beast/denizen.beast.vow-of-beastkin.jpg'
import img59 from './cards/beast/denizen.beast.vow-of-poverty.jpg'
import img60 from './cards/beast/denizen.beast.vow-of-union.jpg'
import img61 from './cards/beast/denizen.beast.walled-garden.jpg'
import img62 from './cards/beast/denizen.beast.war-tortoise.jpg'
import img63 from './cards/beast/denizen.beast.wild-allies.jpg'
import img64 from './cards/beast/denizen.beast.wild-cry.jpg'
import img65 from './cards/beast/denizen.beast.wolves.jpg'
import img66 from './cards/discord/denizen.discord.a-small-favor.jpg'
import img67 from './cards/discord/denizen.discord.assassin.jpg'
import img68 from './cards/discord/denizen.discord.bandit-chief.jpg'
import img69 from './cards/discord/denizen.discord.beast-tamer.jpg'
import img70 from './cards/discord/denizen.discord.blackmail.jpg'
import img71 from './cards/discord/denizen.discord.boiling-lake.jpg'
import img72 from './cards/discord/denizen.discord.book-burning.jpg'
import img73 from './cards/discord/denizen.discord.chaos-cult.jpg'
import img74 from './cards/discord/denizen.discord.charlatan.jpg'
import img75 from './cards/discord/denizen.discord.cracked-sage.jpg'
import img76 from './cards/discord/denizen.discord.disgraced-captain.jpg'
import img77 from './cards/discord/denizen.discord.dissent.jpg'
import img78 from './cards/discord/denizen.discord.downtrodden.jpg'
import img79 from './cards/discord/denizen.discord.enchantress.jpg'
import img80 from './cards/discord/denizen.discord.false-prophet.jpg'
import img81 from './cards/discord/denizen.discord.gambling-hall.jpg'
import img82 from './cards/discord/denizen.discord.gossip.jpg'
import img83 from './cards/discord/denizen.discord.insomnia.jpg'
import img84 from './cards/discord/denizen.discord.key-to-the-city.jpg'
import img85 from './cards/discord/denizen.discord.mercenaries.jpg'
import img86 from './cards/discord/denizen.discord.naysayers.jpg'
import img87 from './cards/discord/denizen.discord.relic-thief.jpg'
import img88 from './cards/discord/denizen.discord.riots.jpg'
import img89 from './cards/discord/denizen.discord.royal-ambitions.jpg'
import img90 from './cards/discord/denizen.discord.salt-the-earth.jpg'
import img91 from './cards/discord/denizen.discord.scryer.jpg'
import img92 from './cards/discord/denizen.discord.second-wind.jpg'
import img93 from './cards/discord/denizen.discord.silver-tongue.jpg'
import img94 from './cards/discord/denizen.discord.slander.jpg'
import img95 from './cards/discord/denizen.discord.sleight-of-hand.jpg'
import img96 from './cards/discord/denizen.discord.sneak-attack.jpg'
import img97 from './cards/discord/denizen.discord.vow-of-renewal.jpg'
import img98 from './cards/discord/denizen.discord.zealots.jpg'
import img99 from './cards/hearth/denizen.hearth.a-round-of-ale.jpg'
import img100 from './cards/hearth/denizen.hearth.armed-mob.jpg'
import img101 from './cards/hearth/denizen.hearth.awaited-return.jpg'
import img102 from './cards/hearth/denizen.hearth.ballot-box.jpg'
import img103 from './cards/hearth/denizen.hearth.book-binders.jpg'
import img104 from './cards/hearth/denizen.hearth.charming-friend.jpg'
import img105 from './cards/hearth/denizen.hearth.crop-rotation.jpg'
import img106 from './cards/hearth/denizen.hearth.deed-writer.jpg'
import img107 from './cards/hearth/denizen.hearth.extra-provisions.jpg'
import img108 from './cards/hearth/denizen.hearth.fabled-feast.jpg'
import img109 from './cards/hearth/denizen.hearth.family-heirloom.jpg'
import img110 from './cards/hearth/denizen.hearth.hearts-and-minds.jpg'
import img111 from './cards/hearth/denizen.hearth.herald.jpg'
import img112 from './cards/hearth/denizen.hearth.homesteaders.jpg'
import img113 from './cards/hearth/denizen.hearth.hospital.jpg'
import img114 from './cards/hearth/denizen.hearth.land-warden.jpg'
import img115 from './cards/hearth/denizen.hearth.levelers.jpg'
import img116 from './cards/hearth/denizen.hearth.marriage.jpg'
import img117 from './cards/hearth/denizen.hearth.memory-of-home.jpg'
import img118 from './cards/hearth/denizen.hearth.news-from-afar.jpg'
import img119 from './cards/hearth/denizen.hearth.relic-breaker.jpg'
import img120 from './cards/hearth/denizen.hearth.rowdy-pub.jpg'
import img121 from './cards/hearth/denizen.hearth.saddle-makers.jpg'
import img122 from './cards/hearth/denizen.hearth.salad-days.jpg'
import img123 from './cards/hearth/denizen.hearth.storyteller.jpg'
import img124 from './cards/hearth/denizen.hearth.tavern-songs.jpg'
import img125 from './cards/hearth/denizen.hearth.the-great-levy.jpg'
import img126 from './cards/hearth/denizen.hearth.tinkers-fair.jpg'
import img127 from './cards/hearth/denizen.hearth.traveling-doctor.jpg'
import img128 from './cards/hearth/denizen.hearth.village-constable.jpg'
import img129 from './cards/hearth/denizen.hearth.vow-of-peace.jpg'
import img130 from './cards/hearth/denizen.hearth.wayside-inn.jpg'
import img131 from './cards/hearth/denizen.hearth.welcoming-party.jpg'
import img132 from './cards/nomad/denizen.nomad.a-fast-steed.jpg'
import img133 from './cards/nomad/denizen.nomad.ancient-binding.jpg'
import img134 from './cards/nomad/denizen.nomad.ancient-bloodline.jpg'
import img135 from './cards/nomad/denizen.nomad.ancient-pact.jpg'
import img136 from './cards/nomad/denizen.nomad.convoys.jpg'
import img137 from './cards/nomad/denizen.nomad.elders.jpg'
import img138 from './cards/nomad/denizen.nomad.faithful-friend.jpg'
import img139 from './cards/nomad/denizen.nomad.family-wagon.jpg'
import img140 from './cards/nomad/denizen.nomad.great-crusade.jpg'
import img141 from './cards/nomad/denizen.nomad.great-herd.jpg'
import img142 from './cards/nomad/denizen.nomad.horse-archers.jpg'
import img143 from './cards/nomad/denizen.nomad.hospitality.jpg'
import img144 from './cards/nomad/denizen.nomad.lancers.jpg'
import img145 from './cards/nomad/denizen.nomad.lost-tongue.jpg'
import img146 from './cards/nomad/denizen.nomad.mountain-giant.jpg'
import img147 from './cards/nomad/denizen.nomad.mounted-patrol.jpg'
import img148 from './cards/nomad/denizen.nomad.oracle.jpg'
import img149 from './cards/nomad/denizen.nomad.pilgrimage.jpg'
import img150 from './cards/nomad/denizen.nomad.rain-boots.jpg'
import img151 from './cards/nomad/denizen.nomad.relic-worship.jpg'
import img152 from './cards/nomad/denizen.nomad.resettle.jpg'
import img153 from './cards/nomad/denizen.nomad.rival-khan.jpg'
import img154 from './cards/nomad/denizen.nomad.sacred-ground.jpg'
import img155 from './cards/nomad/denizen.nomad.special-envoy.jpg'
import img156 from './cards/nomad/denizen.nomad.spell-breaker.jpg'
import img157 from './cards/nomad/denizen.nomad.storm-caller.jpg'
import img158 from './cards/nomad/denizen.nomad.tents.jpg'
import img159 from './cards/nomad/denizen.nomad.the-gathering.jpg'
import img160 from './cards/nomad/denizen.nomad.twin-brother.jpg'
import img161 from './cards/nomad/denizen.nomad.vow-of-kinship.jpg'
import img162 from './cards/nomad/denizen.nomad.warning-signals.jpg'
import img163 from './cards/nomad/denizen.nomad.way-station.jpg'
import img164 from './cards/nomad/denizen.nomad.wild-mounts.jpg'
import img165 from './cards/order/denizen.order.battle-honors.jpg'
import img166 from './cards/order/denizen.order.bear-traps.jpg'
import img167 from './cards/order/denizen.order.captains.jpg'
import img168 from './cards/order/denizen.order.code-of-honor.jpg'
import img169 from './cards/order/denizen.order.council-seat.jpg'
import img170 from './cards/order/denizen.order.curfew.jpg'
import img171 from './cards/order/denizen.order.encirclement.jpg'
import img172 from './cards/order/denizen.order.field-promotion.jpg'
import img173 from './cards/order/denizen.order.forced-labor.jpg'
import img174 from './cards/order/denizen.order.garrison.jpg'
import img175 from './cards/order/denizen.order.hunting-party.jpg'
import img176 from './cards/order/denizen.order.keep.jpg'
import img177 from './cards/order/denizen.order.knights-errant.jpg'
import img178 from './cards/order/denizen.order.longbows.jpg'
import img179 from './cards/order/denizen.order.martial-culture.jpg'
import img180 from './cards/order/denizen.order.messenger.jpg'
import img181 from './cards/order/denizen.order.military-parade.jpg'
import img182 from './cards/order/denizen.order.outriders.jpg'
import img183 from './cards/order/denizen.order.palanquin.jpg'
import img184 from './cards/order/denizen.order.peace-envoy.jpg'
import img185 from './cards/order/denizen.order.pressgangs.jpg'
import img186 from './cards/order/denizen.order.relic-hunter.jpg'
import img187 from './cards/order/denizen.order.royal-tax.jpg'
import img188 from './cards/order/denizen.order.scouts.jpg'
import img189 from './cards/order/denizen.order.secret-police.jpg'
import img190 from './cards/order/denizen.order.shield-wall.jpg'
import img191 from './cards/order/denizen.order.siege-engines.jpg'
import img192 from './cards/order/denizen.order.specialist.jpg'
import img193 from './cards/order/denizen.order.toll-roads.jpg'
import img194 from './cards/order/denizen.order.tome-guardians.jpg'
import img195 from './cards/order/denizen.order.tyrant.jpg'
import img196 from './cards/order/denizen.order.vow-of-obedience.jpg'
import img197 from './cards/order/denizen.order.wrestlers.jpg'
import img198 from './cards/relic.bandit-crown.jpg'
import img199 from './cards/relic.book-of-records.jpg'
import img200 from './cards/relic.brass-horse.jpg'
import img201 from './cards/relic.circlet-of-command.jpg'
import img202 from './cards/relic.cracked-horn.jpg'
import img203 from './cards/relic.cup-of-plenty.jpg'
import img204 from './cards/relic.cursed-cauldron.jpg'
import img205 from './cards/relic.dowsing-sticks.jpg'
import img206 from './cards/relic.dragonskin-drum.jpg'
import img207 from './cards/relic.grand-mask.jpg'
import img208 from './cards/relic.grand-scepter.jpg'
import img209 from './cards/relic.horned-mask.jpg'
import img210 from './cards/relic.ivory-eye.jpg'
import img211 from './cards/relic.map.jpg'
import img212 from './cards/relic.obsidian-cage.jpg'
import img213 from './cards/relic.oracular-pig.jpg'
import img214 from './cards/relic.ring-of-devotion.jpg'
import img215 from './cards/relic.skeleton-key.jpg'
import img216 from './cards/relic.sticky-fire.jpg'
import img217 from './cards/relic.truthful-harp.jpg'
import img218 from './cards/relic.whistle.jpg'
import img219 from './cards/site.ancient-city.jpg'
import img220 from './cards/site.barren-coast.jpg'
import img221 from './cards/site.buried-giant.jpg'
import img222 from './cards/site.charming-valley.jpg'
import img223 from './cards/site.deep-woods.jpg'
import img224 from './cards/site.drowned-city.jpg'
import img225 from './cards/site.fertile-valley.jpg'
import img226 from './cards/site.great-slums.jpg'
import img227 from './cards/site.lush-coast.jpg'
import img228 from './cards/site.marshes.jpg'
import img229 from './cards/site.mine.jpg'
import img230 from './cards/site.mountain.jpg'
import img231 from './cards/site.narrow-pass.jpg'
import img232 from './cards/site.plains.jpg'
import img233 from './cards/site.river.jpg'
import img234 from './cards/site.rocky-coast.jpg'
import img235 from './cards/site.salt-flats.jpg'
import img236 from './cards/site.shrouded-wood.jpg'
import img237 from './cards/site.standing-stones.jpg'
import img238 from './cards/site.steppe.jpg'
import img239 from './cards/site.the-hidden-place.jpg'
import img240 from './cards/site.the-tribunal.jpg'
import img241 from './cards/site.wastes.jpg'
import img242 from './cards/vision.conquest.jpg'
import img243 from './cards/vision.conspiracy.jpg'
import img244 from './cards/vision.faith.jpg'
import img245 from './cards/vision.rebellion.jpg'
import img246 from './cards/vision.sanctuary.jpg'
import img247 from './backs/denizen.jpg'
import img248 from './backs/relic.jpg'
import img249 from './backs/site.jpg'
import img250 from './backs/vision.jpg'
import img251 from './pieces/pawn.black.svg'
import img252 from './pieces/pawn.blue.svg'
import img253 from './pieces/pawn.purple.svg'
import img254 from './pieces/pawn.red.svg'
import img255 from './pieces/pawn.white.svg'
import img256 from './pieces/pawn.yellow.svg'
import img257 from './pieces/warband.black.svg'
import img258 from './pieces/warband.blue.svg'
import img259 from './pieces/warband.purple.svg'
import img260 from './pieces/warband.red.svg'
import img261 from './pieces/warband.white.svg'
import img262 from './pieces/warband.yellow.svg'
import img263 from './actions/action.campaign.svg'
import img264 from './actions/action.muster.svg'
import img265 from './actions/action.recover.svg'
import img266 from './actions/action.search.svg'
import img267 from './actions/action.trade.svg'
import img268 from './actions/action.travel.svg'
import img269 from './dice/attack.hollow-sword.svg'
import img270 from './dice/attack.skull.svg'
import img271 from './dice/attack.sword.svg'
import img272 from './dice/defense.blank.svg'
import img273 from './dice/defense.doubling.svg'
import img274 from './dice/defense.shield.svg'
import img275 from './dice/defense.two-shields.svg'
import img276 from './dice/end.1.svg'
import img277 from './dice/end.2.svg'
import img278 from './dice/end.3.svg'
import img279 from './dice/end.4.svg'
import img280 from './dice/end.5.svg'
import img281 from './dice/end.6.svg'
import img282 from './suits/arcane.svg'
import img283 from './suits/beast.svg'
import img284 from './suits/discord.svg'
import img285 from './suits/hearth.svg'
import img286 from './suits/nomad.svg'
import img287 from './suits/order.svg'
import img288 from './playerBoards/avatar.chancellor.jpg'
import img289 from './playerBoards/avatar.citizen.black.jpg'
import img290 from './playerBoards/avatar.citizen.blue.jpg'
import img291 from './playerBoards/avatar.citizen.red.jpg'
import img292 from './playerBoards/avatar.citizen.white.jpg'
import img293 from './playerBoards/avatar.citizen.yellow.jpg'
import img294 from './playerBoards/avatar.exile.black.jpg'
import img295 from './playerBoards/avatar.exile.blue.jpg'
import img296 from './playerBoards/avatar.exile.red.jpg'
import img297 from './playerBoards/avatar.exile.white.jpg'
import img298 from './playerBoards/avatar.exile.yellow.jpg'
import img299 from './playerBoards/title.chancellor.jpg'
import img300 from './playerBoards/title.citizen.jpg'
import img301 from './playerBoards/title.exile.black.jpg'
import img302 from './playerBoards/title.exile.blue.jpg'
import img303 from './playerBoards/title.exile.red.jpg'
import img304 from './playerBoards/title.exile.white.jpg'
import img305 from './playerBoards/title.exile.yellow.jpg'
import img306 from './tiles/goal.devotion.jpg'
import img307 from './tiles/goal.protection.jpg'
import img308 from './tiles/goal.supremacy.jpg'
import img309 from './tiles/goal.thePeople.jpg'
import img310 from './tiles/marker.visions.png'
import img311 from './tiles/oathkeeper.jpg'
import img312 from './tiles/oathkeeper.usurper.jpg'
import img313 from './tiles/reliquary.placard.jpg'
import img314 from './tiles/token.favor.png'
import img315 from './tiles/token.secret.png'
import img316 from './tiles/track.chancellor.jpg'
import img317 from './tiles/track.citizen.jpg'
import img318 from './tiles/track.exile.jpg'
import img319 from './tiles/trait.brutal.jpg'
import img320 from './tiles/trait.careless.jpg'
import img321 from './tiles/trait.decadent.jpg'
import img322 from './tiles/trait.greedy.jpg'
import img323 from './banners/darkestSecret.jpg'
import img324 from './banners/peoplesFavor.jpg'
import img325 from './banners/peoplesFavor.mob.jpg'

/** 247 files under `cards/`. */
export const cardFiles: Record<string, string> = {
    './cards/arcane/denizen.arcane.acting-troupe.jpg': img0,
    './cards/arcane/denizen.arcane.alchemist.jpg': img1,
    './cards/arcane/denizen.arcane.augury.jpg': img2,
    './cards/arcane/denizen.arcane.bewitch.jpg': img3,
    './cards/arcane/denizen.arcane.billowing-fog.jpg': img4,
    './cards/arcane/denizen.arcane.blood-pact.jpg': img5,
    './cards/arcane/denizen.arcane.cracking-ground.jpg': img6,
    './cards/arcane/denizen.arcane.dazzle.jpg': img7,
    './cards/arcane/denizen.arcane.dream-thief.jpg': img8,
    './cards/arcane/denizen.arcane.fire-talkers.jpg': img9,
    './cards/arcane/denizen.arcane.forgotten-vault.jpg': img10,
    './cards/arcane/denizen.arcane.gleaming-armor.jpg': img11,
    './cards/arcane/denizen.arcane.initiation-rite.jpg': img12,
    './cards/arcane/denizen.arcane.inquisitor.jpg': img13,
    './cards/arcane/denizen.arcane.jinx.jpg': img14,
    './cards/arcane/denizen.arcane.kindred-warriors.jpg': img15,
    './cards/arcane/denizen.arcane.magicians-code.jpg': img16,
    './cards/arcane/denizen.arcane.map-library.jpg': img17,
    './cards/arcane/denizen.arcane.master-of-disguise.jpg': img18,
    './cards/arcane/denizen.arcane.observatory.jpg': img19,
    './cards/arcane/denizen.arcane.plague-engines.jpg': img20,
    './cards/arcane/denizen.arcane.portal.jpg': img21,
    './cards/arcane/denizen.arcane.revelation.jpg': img22,
    './cards/arcane/denizen.arcane.rusting-ray.jpg': img23,
    './cards/arcane/denizen.arcane.sealing-ward.jpg': img24,
    './cards/arcane/denizen.arcane.secret-signal.jpg': img25,
    './cards/arcane/denizen.arcane.spirit-snare.jpg': img26,
    './cards/arcane/denizen.arcane.taming-charm.jpg': img27,
    './cards/arcane/denizen.arcane.terror-spells.jpg': img28,
    './cards/arcane/denizen.arcane.tutor.jpg': img29,
    './cards/arcane/denizen.arcane.vow-of-silence.jpg': img30,
    './cards/arcane/denizen.arcane.witchs-bargain.jpg': img31,
    './cards/arcane/denizen.arcane.wizard-school.jpg': img32,
    './cards/beast/denizen.beast.animal-host.jpg': img33,
    './cards/beast/denizen.beast.animal-playmates.jpg': img34,
    './cards/beast/denizen.beast.birdsong.jpg': img35,
    './cards/beast/denizen.beast.bracken.jpg': img36,
    './cards/beast/denizen.beast.errand-boy.jpg': img37,
    './cards/beast/denizen.beast.fae-merchant.jpg': img38,
    './cards/beast/denizen.beast.forest-council.jpg': img39,
    './cards/beast/denizen.beast.forest-paths.jpg': img40,
    './cards/beast/denizen.beast.giant-python.jpg': img41,
    './cards/beast/denizen.beast.grasping-vines.jpg': img42,
    './cards/beast/denizen.beast.insect-swarm.jpg': img43,
    './cards/beast/denizen.beast.long-lost-heir.jpg': img44,
    './cards/beast/denizen.beast.marsh-spirit.jpg': img45,
    './cards/beast/denizen.beast.memory-of-nature.jpg': img46,
    './cards/beast/denizen.beast.mushrooms.jpg': img47,
    './cards/beast/denizen.beast.nature-worship.jpg': img48,
    './cards/beast/denizen.beast.new-growth.jpg': img49,
    './cards/beast/denizen.beast.pied-piper.jpg': img50,
    './cards/beast/denizen.beast.rangers.jpg': img51,
    './cards/beast/denizen.beast.roving-terror.jpg': img52,
    './cards/beast/denizen.beast.second-chance.jpg': img53,
    './cards/beast/denizen.beast.small-friends.jpg': img54,
    './cards/beast/denizen.beast.the-old-oak.jpg': img55,
    './cards/beast/denizen.beast.threatening-roar.jpg': img56,
    './cards/beast/denizen.beast.true-names.jpg': img57,
    './cards/beast/denizen.beast.vow-of-beastkin.jpg': img58,
    './cards/beast/denizen.beast.vow-of-poverty.jpg': img59,
    './cards/beast/denizen.beast.vow-of-union.jpg': img60,
    './cards/beast/denizen.beast.walled-garden.jpg': img61,
    './cards/beast/denizen.beast.war-tortoise.jpg': img62,
    './cards/beast/denizen.beast.wild-allies.jpg': img63,
    './cards/beast/denizen.beast.wild-cry.jpg': img64,
    './cards/beast/denizen.beast.wolves.jpg': img65,
    './cards/discord/denizen.discord.a-small-favor.jpg': img66,
    './cards/discord/denizen.discord.assassin.jpg': img67,
    './cards/discord/denizen.discord.bandit-chief.jpg': img68,
    './cards/discord/denizen.discord.beast-tamer.jpg': img69,
    './cards/discord/denizen.discord.blackmail.jpg': img70,
    './cards/discord/denizen.discord.boiling-lake.jpg': img71,
    './cards/discord/denizen.discord.book-burning.jpg': img72,
    './cards/discord/denizen.discord.chaos-cult.jpg': img73,
    './cards/discord/denizen.discord.charlatan.jpg': img74,
    './cards/discord/denizen.discord.cracked-sage.jpg': img75,
    './cards/discord/denizen.discord.disgraced-captain.jpg': img76,
    './cards/discord/denizen.discord.dissent.jpg': img77,
    './cards/discord/denizen.discord.downtrodden.jpg': img78,
    './cards/discord/denizen.discord.enchantress.jpg': img79,
    './cards/discord/denizen.discord.false-prophet.jpg': img80,
    './cards/discord/denizen.discord.gambling-hall.jpg': img81,
    './cards/discord/denizen.discord.gossip.jpg': img82,
    './cards/discord/denizen.discord.insomnia.jpg': img83,
    './cards/discord/denizen.discord.key-to-the-city.jpg': img84,
    './cards/discord/denizen.discord.mercenaries.jpg': img85,
    './cards/discord/denizen.discord.naysayers.jpg': img86,
    './cards/discord/denizen.discord.relic-thief.jpg': img87,
    './cards/discord/denizen.discord.riots.jpg': img88,
    './cards/discord/denizen.discord.royal-ambitions.jpg': img89,
    './cards/discord/denizen.discord.salt-the-earth.jpg': img90,
    './cards/discord/denizen.discord.scryer.jpg': img91,
    './cards/discord/denizen.discord.second-wind.jpg': img92,
    './cards/discord/denizen.discord.silver-tongue.jpg': img93,
    './cards/discord/denizen.discord.slander.jpg': img94,
    './cards/discord/denizen.discord.sleight-of-hand.jpg': img95,
    './cards/discord/denizen.discord.sneak-attack.jpg': img96,
    './cards/discord/denizen.discord.vow-of-renewal.jpg': img97,
    './cards/discord/denizen.discord.zealots.jpg': img98,
    './cards/hearth/denizen.hearth.a-round-of-ale.jpg': img99,
    './cards/hearth/denizen.hearth.armed-mob.jpg': img100,
    './cards/hearth/denizen.hearth.awaited-return.jpg': img101,
    './cards/hearth/denizen.hearth.ballot-box.jpg': img102,
    './cards/hearth/denizen.hearth.book-binders.jpg': img103,
    './cards/hearth/denizen.hearth.charming-friend.jpg': img104,
    './cards/hearth/denizen.hearth.crop-rotation.jpg': img105,
    './cards/hearth/denizen.hearth.deed-writer.jpg': img106,
    './cards/hearth/denizen.hearth.extra-provisions.jpg': img107,
    './cards/hearth/denizen.hearth.fabled-feast.jpg': img108,
    './cards/hearth/denizen.hearth.family-heirloom.jpg': img109,
    './cards/hearth/denizen.hearth.hearts-and-minds.jpg': img110,
    './cards/hearth/denizen.hearth.herald.jpg': img111,
    './cards/hearth/denizen.hearth.homesteaders.jpg': img112,
    './cards/hearth/denizen.hearth.hospital.jpg': img113,
    './cards/hearth/denizen.hearth.land-warden.jpg': img114,
    './cards/hearth/denizen.hearth.levelers.jpg': img115,
    './cards/hearth/denizen.hearth.marriage.jpg': img116,
    './cards/hearth/denizen.hearth.memory-of-home.jpg': img117,
    './cards/hearth/denizen.hearth.news-from-afar.jpg': img118,
    './cards/hearth/denizen.hearth.relic-breaker.jpg': img119,
    './cards/hearth/denizen.hearth.rowdy-pub.jpg': img120,
    './cards/hearth/denizen.hearth.saddle-makers.jpg': img121,
    './cards/hearth/denizen.hearth.salad-days.jpg': img122,
    './cards/hearth/denizen.hearth.storyteller.jpg': img123,
    './cards/hearth/denizen.hearth.tavern-songs.jpg': img124,
    './cards/hearth/denizen.hearth.the-great-levy.jpg': img125,
    './cards/hearth/denizen.hearth.tinkers-fair.jpg': img126,
    './cards/hearth/denizen.hearth.traveling-doctor.jpg': img127,
    './cards/hearth/denizen.hearth.village-constable.jpg': img128,
    './cards/hearth/denizen.hearth.vow-of-peace.jpg': img129,
    './cards/hearth/denizen.hearth.wayside-inn.jpg': img130,
    './cards/hearth/denizen.hearth.welcoming-party.jpg': img131,
    './cards/nomad/denizen.nomad.a-fast-steed.jpg': img132,
    './cards/nomad/denizen.nomad.ancient-binding.jpg': img133,
    './cards/nomad/denizen.nomad.ancient-bloodline.jpg': img134,
    './cards/nomad/denizen.nomad.ancient-pact.jpg': img135,
    './cards/nomad/denizen.nomad.convoys.jpg': img136,
    './cards/nomad/denizen.nomad.elders.jpg': img137,
    './cards/nomad/denizen.nomad.faithful-friend.jpg': img138,
    './cards/nomad/denizen.nomad.family-wagon.jpg': img139,
    './cards/nomad/denizen.nomad.great-crusade.jpg': img140,
    './cards/nomad/denizen.nomad.great-herd.jpg': img141,
    './cards/nomad/denizen.nomad.horse-archers.jpg': img142,
    './cards/nomad/denizen.nomad.hospitality.jpg': img143,
    './cards/nomad/denizen.nomad.lancers.jpg': img144,
    './cards/nomad/denizen.nomad.lost-tongue.jpg': img145,
    './cards/nomad/denizen.nomad.mountain-giant.jpg': img146,
    './cards/nomad/denizen.nomad.mounted-patrol.jpg': img147,
    './cards/nomad/denizen.nomad.oracle.jpg': img148,
    './cards/nomad/denizen.nomad.pilgrimage.jpg': img149,
    './cards/nomad/denizen.nomad.rain-boots.jpg': img150,
    './cards/nomad/denizen.nomad.relic-worship.jpg': img151,
    './cards/nomad/denizen.nomad.resettle.jpg': img152,
    './cards/nomad/denizen.nomad.rival-khan.jpg': img153,
    './cards/nomad/denizen.nomad.sacred-ground.jpg': img154,
    './cards/nomad/denizen.nomad.special-envoy.jpg': img155,
    './cards/nomad/denizen.nomad.spell-breaker.jpg': img156,
    './cards/nomad/denizen.nomad.storm-caller.jpg': img157,
    './cards/nomad/denizen.nomad.tents.jpg': img158,
    './cards/nomad/denizen.nomad.the-gathering.jpg': img159,
    './cards/nomad/denizen.nomad.twin-brother.jpg': img160,
    './cards/nomad/denizen.nomad.vow-of-kinship.jpg': img161,
    './cards/nomad/denizen.nomad.warning-signals.jpg': img162,
    './cards/nomad/denizen.nomad.way-station.jpg': img163,
    './cards/nomad/denizen.nomad.wild-mounts.jpg': img164,
    './cards/order/denizen.order.battle-honors.jpg': img165,
    './cards/order/denizen.order.bear-traps.jpg': img166,
    './cards/order/denizen.order.captains.jpg': img167,
    './cards/order/denizen.order.code-of-honor.jpg': img168,
    './cards/order/denizen.order.council-seat.jpg': img169,
    './cards/order/denizen.order.curfew.jpg': img170,
    './cards/order/denizen.order.encirclement.jpg': img171,
    './cards/order/denizen.order.field-promotion.jpg': img172,
    './cards/order/denizen.order.forced-labor.jpg': img173,
    './cards/order/denizen.order.garrison.jpg': img174,
    './cards/order/denizen.order.hunting-party.jpg': img175,
    './cards/order/denizen.order.keep.jpg': img176,
    './cards/order/denizen.order.knights-errant.jpg': img177,
    './cards/order/denizen.order.longbows.jpg': img178,
    './cards/order/denizen.order.martial-culture.jpg': img179,
    './cards/order/denizen.order.messenger.jpg': img180,
    './cards/order/denizen.order.military-parade.jpg': img181,
    './cards/order/denizen.order.outriders.jpg': img182,
    './cards/order/denizen.order.palanquin.jpg': img183,
    './cards/order/denizen.order.peace-envoy.jpg': img184,
    './cards/order/denizen.order.pressgangs.jpg': img185,
    './cards/order/denizen.order.relic-hunter.jpg': img186,
    './cards/order/denizen.order.royal-tax.jpg': img187,
    './cards/order/denizen.order.scouts.jpg': img188,
    './cards/order/denizen.order.secret-police.jpg': img189,
    './cards/order/denizen.order.shield-wall.jpg': img190,
    './cards/order/denizen.order.siege-engines.jpg': img191,
    './cards/order/denizen.order.specialist.jpg': img192,
    './cards/order/denizen.order.toll-roads.jpg': img193,
    './cards/order/denizen.order.tome-guardians.jpg': img194,
    './cards/order/denizen.order.tyrant.jpg': img195,
    './cards/order/denizen.order.vow-of-obedience.jpg': img196,
    './cards/order/denizen.order.wrestlers.jpg': img197,
    './cards/relic.bandit-crown.jpg': img198,
    './cards/relic.book-of-records.jpg': img199,
    './cards/relic.brass-horse.jpg': img200,
    './cards/relic.circlet-of-command.jpg': img201,
    './cards/relic.cracked-horn.jpg': img202,
    './cards/relic.cup-of-plenty.jpg': img203,
    './cards/relic.cursed-cauldron.jpg': img204,
    './cards/relic.dowsing-sticks.jpg': img205,
    './cards/relic.dragonskin-drum.jpg': img206,
    './cards/relic.grand-mask.jpg': img207,
    './cards/relic.grand-scepter.jpg': img208,
    './cards/relic.horned-mask.jpg': img209,
    './cards/relic.ivory-eye.jpg': img210,
    './cards/relic.map.jpg': img211,
    './cards/relic.obsidian-cage.jpg': img212,
    './cards/relic.oracular-pig.jpg': img213,
    './cards/relic.ring-of-devotion.jpg': img214,
    './cards/relic.skeleton-key.jpg': img215,
    './cards/relic.sticky-fire.jpg': img216,
    './cards/relic.truthful-harp.jpg': img217,
    './cards/relic.whistle.jpg': img218,
    './cards/site.ancient-city.jpg': img219,
    './cards/site.barren-coast.jpg': img220,
    './cards/site.buried-giant.jpg': img221,
    './cards/site.charming-valley.jpg': img222,
    './cards/site.deep-woods.jpg': img223,
    './cards/site.drowned-city.jpg': img224,
    './cards/site.fertile-valley.jpg': img225,
    './cards/site.great-slums.jpg': img226,
    './cards/site.lush-coast.jpg': img227,
    './cards/site.marshes.jpg': img228,
    './cards/site.mine.jpg': img229,
    './cards/site.mountain.jpg': img230,
    './cards/site.narrow-pass.jpg': img231,
    './cards/site.plains.jpg': img232,
    './cards/site.river.jpg': img233,
    './cards/site.rocky-coast.jpg': img234,
    './cards/site.salt-flats.jpg': img235,
    './cards/site.shrouded-wood.jpg': img236,
    './cards/site.standing-stones.jpg': img237,
    './cards/site.steppe.jpg': img238,
    './cards/site.the-hidden-place.jpg': img239,
    './cards/site.the-tribunal.jpg': img240,
    './cards/site.wastes.jpg': img241,
    './cards/vision.conquest.jpg': img242,
    './cards/vision.conspiracy.jpg': img243,
    './cards/vision.faith.jpg': img244,
    './cards/vision.rebellion.jpg': img245,
    './cards/vision.sanctuary.jpg': img246
}

/** 4 files under `backs/`. */
export const backFiles: Record<string, string> = {
    './backs/denizen.jpg': img247,
    './backs/relic.jpg': img248,
    './backs/site.jpg': img249,
    './backs/vision.jpg': img250
}

/** 12 files under `pieces/`. */
export const pieceFiles: Record<string, string> = {
    './pieces/pawn.black.svg': img251,
    './pieces/pawn.blue.svg': img252,
    './pieces/pawn.purple.svg': img253,
    './pieces/pawn.red.svg': img254,
    './pieces/pawn.white.svg': img255,
    './pieces/pawn.yellow.svg': img256,
    './pieces/warband.black.svg': img257,
    './pieces/warband.blue.svg': img258,
    './pieces/warband.purple.svg': img259,
    './pieces/warband.red.svg': img260,
    './pieces/warband.white.svg': img261,
    './pieces/warband.yellow.svg': img262
}

/** 6 files under `actions/`. */
export const actionFiles: Record<string, string> = {
    './actions/action.campaign.svg': img263,
    './actions/action.muster.svg': img264,
    './actions/action.recover.svg': img265,
    './actions/action.search.svg': img266,
    './actions/action.trade.svg': img267,
    './actions/action.travel.svg': img268
}

/** 13 files under `dice/`. */
export const diceFiles: Record<string, string> = {
    './dice/attack.hollow-sword.svg': img269,
    './dice/attack.skull.svg': img270,
    './dice/attack.sword.svg': img271,
    './dice/defense.blank.svg': img272,
    './dice/defense.doubling.svg': img273,
    './dice/defense.shield.svg': img274,
    './dice/defense.two-shields.svg': img275,
    './dice/end.1.svg': img276,
    './dice/end.2.svg': img277,
    './dice/end.3.svg': img278,
    './dice/end.4.svg': img279,
    './dice/end.5.svg': img280,
    './dice/end.6.svg': img281
}

/** 6 files under `suits/`. */
export const suitFiles: Record<string, string> = {
    './suits/arcane.svg': img282,
    './suits/beast.svg': img283,
    './suits/discord.svg': img284,
    './suits/hearth.svg': img285,
    './suits/nomad.svg': img286,
    './suits/order.svg': img287
}

/** 18 files under `playerBoards/`. */
export const playerBoardFiles: Record<string, string> = {
    './playerBoards/avatar.chancellor.jpg': img288,
    './playerBoards/avatar.citizen.black.jpg': img289,
    './playerBoards/avatar.citizen.blue.jpg': img290,
    './playerBoards/avatar.citizen.red.jpg': img291,
    './playerBoards/avatar.citizen.white.jpg': img292,
    './playerBoards/avatar.citizen.yellow.jpg': img293,
    './playerBoards/avatar.exile.black.jpg': img294,
    './playerBoards/avatar.exile.blue.jpg': img295,
    './playerBoards/avatar.exile.red.jpg': img296,
    './playerBoards/avatar.exile.white.jpg': img297,
    './playerBoards/avatar.exile.yellow.jpg': img298,
    './playerBoards/title.chancellor.jpg': img299,
    './playerBoards/title.citizen.jpg': img300,
    './playerBoards/title.exile.black.jpg': img301,
    './playerBoards/title.exile.blue.jpg': img302,
    './playerBoards/title.exile.red.jpg': img303,
    './playerBoards/title.exile.white.jpg': img304,
    './playerBoards/title.exile.yellow.jpg': img305
}

/** 17 files under `tiles/`. */
export const tileFiles: Record<string, string> = {
    './tiles/goal.devotion.jpg': img306,
    './tiles/goal.protection.jpg': img307,
    './tiles/goal.supremacy.jpg': img308,
    './tiles/goal.thePeople.jpg': img309,
    './tiles/marker.visions.png': img310,
    './tiles/oathkeeper.jpg': img311,
    './tiles/oathkeeper.usurper.jpg': img312,
    './tiles/reliquary.placard.jpg': img313,
    './tiles/token.favor.png': img314,
    './tiles/token.secret.png': img315,
    './tiles/track.chancellor.jpg': img316,
    './tiles/track.citizen.jpg': img317,
    './tiles/track.exile.jpg': img318,
    './tiles/trait.brutal.jpg': img319,
    './tiles/trait.careless.jpg': img320,
    './tiles/trait.decadent.jpg': img321,
    './tiles/trait.greedy.jpg': img322
}

/** 3 files under `banners/`. */
export const bannerFiles: Record<string, string> = {
    './banners/darkestSecret.jpg': img323,
    './banners/peoplesFavor.jpg': img324,
    './banners/peoplesFavor.mob.jpg': img325
}
