"""Generate src/components/austerlitzData.ts from the transcribed board data.

Usage: python3 -I scripts/build-map-data.py /workspace/artassets/napoleons-triumph

Inputs (under <source>/notes): vassal-skeleton.json (locales and passable approaches),
approach-terrain.json (width and penalty symbols per approach side), locale-features.json
(capacity, hills, stars, set-up locales), roads.json (road groups, crossings, entries) and
impassable-borders.json (borders no piece may cross).
"""
import json
import os
import sys

STAR = {'blue': 'Star.Blue', 'red': 'Star.Red', 'green': 'Star.Green', 'black': 'Star.Black'}
COMMANDER_IDS = {
    'Bessieres': 'bessieres', 'Lannes': 'lannes', 'Murat': 'murat', 'Vandamme': 'vandamme',
    'St. Hilaire': 'st-hilaire', 'Legrand': 'legrand', 'Bagration': 'bagration',
    'Constantine': 'constantine', 'Kollowrath': 'kollowrath', 'Miloradovich': 'miloradovich',
    'Prebyshevsky': 'prebyshevsky', 'Langeron': 'langeron', 'Liechtenstein': 'liechtenstein',
    'Dokhturov': 'dokhturov', 'Kienmayer': 'kienmayer',
}
NAME_FIXES = {'Kobelitz': 'Kobelnitz', 'Losch': 'Lösch', 'Birnhaum': 'Birnbaum', 'Bosorzitz': 'Posorzitz',
              'Narodinach Berg': 'Narovinach Berg', 'Jesera': 'Jesera', 'Simitz': 'Siwitz'}
SYMBOL_ORDER = 'ICAO'


def load(source, name):
    return json.load(open(os.path.join(source, 'notes', name)))


def symbols(codes):
    return ''.join(letter for letter in SYMBOL_ORDER if letter in codes)


def main(source):
    skeleton = load(source, 'vassal-skeleton.json')
    features = load(source, 'locale-features.json')
    roads = load(source, 'roads.json')
    terrain = {entry['approach']: entry for entry in load(source, 'approach-terrain.json')}
    impassable = load(source, 'impassable-borders.json')

    lines = [
        '// Generated by scripts/build-map-data.py from the transcribed board. Do not edit by hand.',
        "import { Side } from './pieces.js'",
        "import { Star, type MapSpec } from './battleMap.js'",
        '',
        'export const AUSTERLITZ_SPEC: MapSpec = {',
        '    locales: [',
    ]
    for number, locale in sorted(features['locales'].items(), key=lambda item: int(item[0])):
        fields = [f'id: {number}', f"capacity: {locale['capacity']}"]
        names = [NAME_FIXES.get(name, name) for name in locale.get('names', [])]
        if names:
            fields.append("name: '" + names[0].replace("'", "\\'") + "'")
        if 'hill' in locale:
            fields.append('hill: true')
        if locale.get('stars'):
            fields.append('stars: [' + ', '.join(STAR[star] for star in locale['stars']) + ']')
        if 'setup' in locale:
            fields.append(f"setup: '{COMMANDER_IDS[locale['setup']]}'")
        lines.append('        { ' + ', '.join(fields) + ' },')
    lines += ['    ],', '    borders: [']
    for approach in skeleton['approaches']:
        entry = terrain[approach['id']]
        a, b = approach['locales']
        by_locale = {side['locale']: side['symbols'] for side in (entry['above'], entry['below'])}
        fields = [f'a: {a}', f'b: {b}']
        if entry['width'] == 'wide':
            fields.append('wide: true')
        if symbols(by_locale[a]):
            fields.append(f"aSymbols: '{symbols(by_locale[a])}'")
        if symbols(by_locale[b]):
            fields.append(f"bSymbols: '{symbols(by_locale[b])}'")
        lines.append('        { ' + ', '.join(fields) + ' },')
    for border in impassable:
        a, b = border['locales']
        fields = [f'a: {a}', f'b: {b}', 'impassable: true']
        if border.get('width') == 'wide':
            fields.append('wide: true')
        lines.append('        { ' + ', '.join(fields) + ' },')
    lines += ['    ],', '    roads: [']
    for crossing in roads['crossings']:
        (a, group_a), (b, group_b) = crossing['ends']
        lines.append(f"        [{a}, {group_a}, {b}, {group_b}, {1 if crossing['main'] else 0}],")
    lines += ['    ],', '    entries: [']
    for entry in roads['entries']:
        side = 'Side.French' if entry['side'] == 'french' else 'Side.Allied'
        lines.append(f"        ['{entry['id']}', {side}, {entry['locale']}, {entry['group']}, {1 if entry['main'] else 0}],")
    lines += ['    ]', '}', '']
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'components', 'austerlitzData.ts')
    open(out, 'w', encoding='utf-8').write('\n'.join(lines))
    print('wrote', os.path.normpath(out), len(features['locales']), 'locales',
          len(skeleton['approaches']) + len(impassable), 'borders', len(roads['crossings']), 'road crossings')


if __name__ == '__main__':
    main(sys.argv[1])
