<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/singleblocker.gltf --types --debug
-->

<script lang="ts">
    import { Group, Mesh, MeshStandardMaterial, Object3D } from 'three'
    import { T } from '@threlte/core'
    import { useGltf } from '@threlte/extras'

    export let stripes: number = 1
    export let onloaded: ((ref: Object3D) => void) | undefined = undefined
    export const group = new Group()

    type GLTFResult = {
        nodes: {
            blankblockerv2: Mesh
            blankblockerv2001: Mesh
        }
        materials: {
            ['Material.001']: MeshStandardMaterial
            ['Material.002']: MeshStandardMaterial
        }
    }

    const gltf = useGltf<GLTFResult>('/BarrierOne.gltf')
</script>

<T is={group} name="barrier" dispose={false} {...$$restProps}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh
            scale={0.05}
            oncreate={(ref) => {
                onloaded?.(group)
                ref.geometry.center()
            }}
            name="outlineMesh"
            geometry={gltf.nodes.blankblockerv2.geometry}
            castShadow
            receiveShadow
        >
            <T.MeshPhysicalMaterial
                color={'#AAAAAA'}
                clearcoat={1}
                clearcoatRoughness={0.33}
            /></T.Mesh
        >

        {#if stripes === 1 || stripes === 3}
            <T.Mesh
                scale={0.05}
                oncreate={(ref) => {
                    ref.geometry.center()
                    ref.position.y = 0.1575
                }}
                depthOffset={-1}
                geometry={gltf.nodes.blankblockerv2001.geometry}
            >
                <T.MeshPhysicalMaterial
                    color={'#EEEEEE'}
                    clearcoat={1}
                    clearcoatRoughness={0.33}
                /></T.Mesh
            >
        {/if}

        {#if stripes === 2 || stripes === 3}
            <T.Mesh
                scale={0.05}
                oncreate={(ref) => {
                    ref.geometry.center()
                    ref.position.y = 0.1575
                    ref.position.z = stripes === 2 ? 0.15 : 0.3
                }}
                depthOffset={-1}
                geometry={gltf.nodes.blankblockerv2001.geometry}
            >
                <T.MeshPhysicalMaterial
                    color={'#EEEEEE'}
                    clearcoat={1}
                    clearcoatRoughness={0.33}
                /></T.Mesh
            >
        {/if}

        {#if stripes === 2 || stripes === 3}
            <T.Mesh
                scale={0.05}
                oncreate={(ref) => {
                    ref.geometry.center()
                    ref.position.y = 0.1575
                    ref.position.z = stripes === 2 ? -0.15 : -0.3
                }}
                depthOffset={-1}
                geometry={gltf.nodes.blankblockerv2001.geometry}
            >
                <T.MeshPhysicalMaterial
                    color={'#EEEEEE'}
                    clearcoat={1}
                    clearcoatRoughness={0.33}
                /></T.Mesh
            >
        {/if}
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {group} />
</T>
