<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/3blocksmoothtexturev2.gltf --types --debug
-->

<script lang="ts">
    import type * as THREE from 'three'
    import { Group, Object3D } from 'three'
    import { T, type Props } from '@threlte/core'
    import { useGltf } from '@threlte/extras'
    // @ts-ignore
    import BarrierMesh from '$lib/3d/Barrier.gltf'

    export let stripes: number = 1
    export let onloaded: ((ref: Object3D) => void) | undefined = undefined
    export const group = new Group()

    type GLTFResult = {
        nodes: {
            roundedblocker: THREE.Mesh
        }
        materials: {
            ['Material.006']: THREE.MeshStandardMaterial
        }
    }

    const gltf = useGltf<GLTFResult>(BarrierMesh)
</script>

<T is={group} name="barrier" dispose={false} {...$$restProps}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh
            scale={0.05}
            oncreate={(ref) => {
                onloaded?.(group)
                ref.geometry.center()
            }}
            name="outlineMesh"
            geometry={gltf.nodes.roundedblocker.geometry}
            material={gltf.materials['Material.006']}
        />
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {group} />
</T>
