<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/barrier.gltf --types --debug
-->

<script lang="ts">
    import { Mesh, MeshStandardMaterial } from 'three'
    import { Group } from 'three'
    import { T } from '@threlte/core'
    import { useGltf } from '@threlte/extras'

    export const ref = new Group()

    type GLTFResult = {
        nodes: {
            Node1: Mesh
        }
        materials: {
            ['01 - Default']: MeshStandardMaterial
        }
    }

    const gltf = useGltf<GLTFResult>('/Barrier.gltf')
</script>

<T is={ref} dispose={false} {...$$restProps}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh
            castShadow
            name="outlineMesh"
            rotation.x={-Math.PI / 2}
            rotation.z={Math.PI / 2}
            geometry={gltf.nodes.Node1.geometry}
            material={new MeshStandardMaterial({
                color: '#999999',
                transparent: true,
                opacity: 1
            })}
        ></T.Mesh>
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {ref} />
</T>
