<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/barrier.gltf --types --debug
-->

<script lang="ts">
    import type * as THREE from 'three'
    import { Group } from 'three'
    import { T } from '@threlte/core'
    import { useGltf } from '@threlte/extras'

    export const ref = new Group()

    type GLTFResult = {
        nodes: {
            Node1: THREE.Mesh
        }
        materials: {
            ['01 - Default']: THREE.MeshStandardMaterial
        }
    }

    const gltf = useGltf<GLTFResult>('/Barrier.gltf')
</script>

<T is={ref} dispose={false} {...$$restProps}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh geometry={gltf.nodes.Node1.geometry} material={gltf.materials['01 - Default']} />
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {ref} />
</T>
