<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/PokerChip.gltf --types --debug
Author: KuoChing.Hsiao (https://sketchfab.com/KuoChing.Hsiao)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/poker-chips-db6c53be86b84b28ba40c485477888e6
Title: Poker Chips
-->

<script lang="ts">
    import * as THREE from 'three'
    import { Group } from 'three'
    import { T, type Props } from '@threlte/core'
    import { useGltf, Text } from '@threlte/extras'

    export const ref = new Group()

    type GLTFResult = {
        nodes: {
            Object_2: THREE.Mesh
        }
        materials: {
            ['default']: THREE.MeshStandardMaterial
        }
    }

    const gltf = useGltf<GLTFResult>('/PokerChip.gltf')
    const material = new THREE.MeshBasicMaterial({ toneMapped: false })
</script>

<T is={ref} dispose={false} {...$$restProps}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh
            scale={0.008}
            geometry={gltf.nodes.Object_2.geometry}
            material={gltf.materials['default']}
            rotation={[0, 0, 0]}
        />
        <Text
            color="#DDDDDD"
            rotation.x={-Math.PI / 2}
            position.y={0.1}
            depthOffset={-1}
            fontSize={0.73}
            fontWeight="bold"
            anchorX="50%"
            anchorY="50%"
            text={'12'}
            {material}
        />
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {ref} />
</T>
