<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/roof.gltf --types --debug
-->

<script lang="ts">
    import { Group, Object3D, Mesh } from 'three'
    import { T } from '@threlte/core'
    import { useGltf } from '@threlte/extras'

    export let onloaded: ((ref: Object3D) => void) | undefined
    export const group = new Group()

    type GLTFResult = {
        nodes: {
            roof: Mesh
        }
        materials: {}
    }

    const gltf = useGltf<GLTFResult>('/roof.gltf')
</script>

<T is={group} dispose={false} {...$$restProps}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh
            castShadow
            oncreate={(ref) => {
                ref.geometry.center()
                onloaded?.(group)
            }}
            name="outlineMesh"
            scale={0.05}
            geometry={gltf.nodes.roof.geometry}
        >
            <T.MeshPhysicalMaterial color={'#333333'} clearcoat={1} clearcoatRoughness={0.33} />
        </T.Mesh>
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {group} />
</T>
