<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/roof.gltf --types --debug
-->

<script lang="ts">
    import type * as THREE from 'three'
    import { Group } from 'three'
    import { T } from '@threlte/core'
    import { useGltf } from '@threlte/extras'

    export const ref = new Group()

    type GLTFResult = {
        nodes: {
            roof: THREE.Mesh
        }
        materials: {}
    }

    const gltf = useGltf<GLTFResult>('/roof.gltf')
</script>

<T is={ref} dispose={false} {...$$restProps}>
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Mesh
            oncreate={(ref) => {
                ref.geometry.center()
            }}
            name="roofMesh"
            scale={0.05}
            geometry={gltf.nodes.roof.geometry}
        >
            <T.MeshPhysicalMaterial color={'#333333'} clearcoat={1} clearcoatRoughness={0.33} />
        </T.Mesh>
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {ref} />
</T>
