<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/scene.gltf --types --transform --debug
Author: PartyBreaker (https://sketchfab.com/PartyBreaker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/top-hat-7ff84e7e989141a6869c7afc12a5e398
Title: Top Hat
-->

<script lang="ts">
    import { Group, Mesh, MeshStandardMaterial, Object3D } from 'three'
    import { T } from '@threlte/core'
    import { useGltf } from '@threlte/extras'

    export let onloaded: ((ref: Object3D) => void) | undefined = undefined
    export const group = new Group()

    type GLTFResult = {
        nodes: {
            Object_4: Mesh
            Object_5: Mesh
        }
        materials: {
            hat1: MeshStandardMaterial
            hat2: MeshStandardMaterial
        }
    }

    const gltf = useGltf<GLTFResult>('/TopHat.gltf')
</script>

<T is={group} dispose={false} {...$$restProps} name="topHat">
    {#await gltf}
        <slot name="fallback" />
    {:then gltf}
        <T.Group position={[-0.33, -0.52, 0.15]}>
            <T.Mesh
                oncreate={(ref) => {
                    ref.geometry.center()
                    onloaded?.(group)
                }}
                name="outlineMesh"
                geometry={gltf.nodes.Object_4.geometry}
                material={gltf.materials.hat1}
                castShadow
            ></T.Mesh>
            <T.Mesh
                geometry={gltf.nodes.Object_5.geometry}
                material={gltf.materials.hat2}
                castShadow
            />
        </T.Group>
    {:catch error}
        <slot name="error" {error} />
    {/await}

    <slot {group} />
</T>
