<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 public/BarrierOne.gltf --types --debug
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      blankblockerv2: THREE.Mesh
      blankblockerv2001: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/public/BarrierOne.gltf')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.blankblockerv2.geometry} material={gltf.materials['Material.001']} />
    <T.Mesh geometry={gltf.nodes.blankblockerv2001.geometry} material={gltf.materials['Material.002']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
