import { Faction } from './factions.js'

export enum ShipKind {
    RE = 'RE',
    CV = 'CV'
}

export interface ShipDefinition {
    id: string
    faction: Faction
    name: string
    kind: ShipKind
    size: number
    exploration: number
    cargo: number
    combat: number
    cost: number
    fast: boolean
    mining: boolean
    research: boolean
}

export const SHIPS: readonly ShipDefinition[] = [
    {
        id: 'consortium-prospector',
        faction: Faction.Consortium,
        name: 'Prospector',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'consortium-prosperity',
        faction: Faction.Consortium,
        name: 'Prosperity',
        kind: ShipKind.RE,
        size: 0,
        exploration: 3,
        cargo: 0,
        combat: 0,
        cost: 5,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'consortium-surveyor',
        faction: Faction.Consortium,
        name: 'Surveyor',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'consortium-guildmaster',
        faction: Faction.Consortium,
        name: 'Guildmaster',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 2,
        combat: 5,
        cost: 9,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'consortium-nostromo',
        faction: Faction.Consortium,
        name: 'Nostromo',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 2,
        combat: 0,
        cost: 7,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'consortium-sapphire',
        faction: Faction.Consortium,
        name: 'Sapphire',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 1,
        combat: 3,
        cost: 7,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'consortium-opal-star',
        faction: Faction.Consortium,
        name: 'Opal Star',
        kind: ShipKind.CV,
        size: 3,
        exploration: 4,
        cargo: 3,
        combat: 3,
        cost: 10,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'consortium-desire',
        faction: Faction.Consortium,
        name: 'Desire',
        kind: ShipKind.CV,
        size: 4,
        exploration: 6,
        cargo: 1,
        combat: 7,
        cost: 12,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'consortium-destiny',
        faction: Faction.Consortium,
        name: 'Destiny',
        kind: ShipKind.CV,
        size: 4,
        exploration: 6,
        cargo: 1,
        combat: 7,
        cost: 12,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'consortium-enterprise',
        faction: Faction.Consortium,
        name: 'Enterprise',
        kind: ShipKind.CV,
        size: 5,
        exploration: 6,
        cargo: 1,
        combat: 8,
        cost: 13,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'consortium-majestic',
        faction: Faction.Consortium,
        name: 'Majestic',
        kind: ShipKind.CV,
        size: 5,
        exploration: 8,
        cargo: 1,
        combat: 9,
        cost: 16,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'consortium-zephyr',
        faction: Faction.Consortium,
        name: 'Zephyr',
        kind: ShipKind.CV,
        size: 5,
        exploration: 3,
        cargo: 4,
        combat: 3,
        cost: 12,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'consortium-aquarius',
        faction: Faction.Consortium,
        name: 'Aquarius',
        kind: ShipKind.CV,
        size: 6,
        exploration: 3,
        cargo: 4,
        combat: 6,
        cost: 15,
        fast: true,
        mining: true,
        research: false
    },
    {
        id: 'consortium-empress',
        faction: Faction.Consortium,
        name: 'Empress',
        kind: ShipKind.CV,
        size: 7,
        exploration: 3,
        cargo: 5,
        combat: 9,
        cost: 16,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'consortium-trident',
        faction: Faction.Consortium,
        name: 'Trident',
        kind: ShipKind.CV,
        size: 7,
        exploration: 8,
        cargo: 1,
        combat: 12,
        cost: 18,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'consortium-neptune',
        faction: Faction.Consortium,
        name: 'Neptune',
        kind: ShipKind.CV,
        size: 8,
        exploration: 10,
        cargo: 1,
        combat: 15,
        cost: 20,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'consortium-colossus',
        faction: Faction.Consortium,
        name: 'Colossus',
        kind: ShipKind.CV,
        size: 10,
        exploration: 9,
        cargo: 6,
        combat: 18,
        cost: 28,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'givers-linnaeus',
        faction: Faction.Givers,
        name: 'Linnaeus',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'givers-humboldt',
        faction: Faction.Givers,
        name: 'Humboldt',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'givers-mendel',
        faction: Faction.Givers,
        name: 'Mendel',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'givers-bougainville',
        faction: Faction.Givers,
        name: 'Bougainville',
        kind: ShipKind.CV,
        size: 2,
        exploration: 2,
        cargo: 2,
        combat: 0,
        cost: 6,
        fast: false,
        mining: false,
        research: true
    },
    {
        id: 'givers-darwin',
        faction: Faction.Givers,
        name: 'Darwin',
        kind: ShipKind.CV,
        size: 2,
        exploration: 4,
        cargo: 1,
        combat: 0,
        cost: 6,
        fast: false,
        mining: false,
        research: true
    },
    {
        id: 'givers-mirabilis',
        faction: Faction.Givers,
        name: 'Mirabilis',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 0,
        combat: 4,
        cost: 6,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'givers-serenity',
        faction: Faction.Givers,
        name: 'Serenity',
        kind: ShipKind.CV,
        size: 3,
        exploration: 3,
        cargo: 3,
        combat: 0,
        cost: 9,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'givers-tempest',
        faction: Faction.Givers,
        name: 'Tempest',
        kind: ShipKind.CV,
        size: 3,
        exploration: 3,
        cargo: 0,
        combat: 6,
        cost: 8,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'givers-osanyin',
        faction: Faction.Givers,
        name: 'Osanyin',
        kind: ShipKind.CV,
        size: 4,
        exploration: 5,
        cargo: 1,
        combat: 7,
        cost: 11,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'givers-viridis',
        faction: Faction.Givers,
        name: 'Viridis',
        kind: ShipKind.CV,
        size: 4,
        exploration: 3,
        cargo: 3,
        combat: 4,
        cost: 11,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'givers-eden',
        faction: Faction.Givers,
        name: 'Eden',
        kind: ShipKind.CV,
        size: 5,
        exploration: 2,
        cargo: 4,
        combat: 4,
        cost: 12,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'givers-typhoon',
        faction: Faction.Givers,
        name: 'Typhoon',
        kind: ShipKind.CV,
        size: 5,
        exploration: 5,
        cargo: 1,
        combat: 8,
        cost: 12,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'givers-artemis',
        faction: Faction.Givers,
        name: 'Artemis',
        kind: ShipKind.CV,
        size: 6,
        exploration: 6,
        cargo: 1,
        combat: 9,
        cost: 13,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'givers-eclipse',
        faction: Faction.Givers,
        name: 'Eclipse',
        kind: ShipKind.CV,
        size: 6,
        exploration: 5,
        cargo: 2,
        combat: 8,
        cost: 14,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'givers-boreas',
        faction: Faction.Givers,
        name: 'Boreas',
        kind: ShipKind.CV,
        size: 7,
        exploration: 7,
        cargo: 1,
        combat: 12,
        cost: 17,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'givers-helios',
        faction: Faction.Givers,
        name: 'Helios',
        kind: ShipKind.CV,
        size: 7,
        exploration: 7,
        cargo: 1,
        combat: 12,
        cost: 17,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'givers-gaia',
        faction: Faction.Givers,
        name: 'Gaia',
        kind: ShipKind.CV,
        size: 9,
        exploration: 9,
        cargo: 3,
        combat: 17,
        cost: 23,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-audax',
        faction: Faction.Praetorians,
        name: 'Audax',
        kind: ShipKind.RE,
        size: 0,
        exploration: 3,
        cargo: 0,
        combat: 0,
        cost: 5,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-fidelis',
        faction: Faction.Praetorians,
        name: 'Fidelis',
        kind: ShipKind.RE,
        size: 0,
        exploration: 3,
        cargo: 0,
        combat: 0,
        cost: 5,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-peregrinus',
        faction: Faction.Praetorians,
        name: 'Peregrinus',
        kind: ShipKind.RE,
        size: 0,
        exploration: 3,
        cargo: 0,
        combat: 0,
        cost: 5,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-noctua',
        faction: Faction.Praetorians,
        name: 'Noctua',
        kind: ShipKind.CV,
        size: 2,
        exploration: 4,
        cargo: 2,
        combat: 3,
        cost: 9,
        fast: false,
        mining: false,
        research: true
    },
    {
        id: 'praetorians-odyssey',
        faction: Faction.Praetorians,
        name: 'Odyssey',
        kind: ShipKind.CV,
        size: 2,
        exploration: 5,
        cargo: 0,
        combat: 6,
        cost: 9,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'praetorians-argonaut',
        faction: Faction.Praetorians,
        name: 'Argonaut',
        kind: ShipKind.CV,
        size: 3,
        exploration: 4,
        cargo: 3,
        combat: 4,
        cost: 11,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-gladiator',
        faction: Faction.Praetorians,
        name: 'Gladiator',
        kind: ShipKind.CV,
        size: 3,
        exploration: 5,
        cargo: 1,
        combat: 8,
        cost: 11,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-centurion',
        faction: Faction.Praetorians,
        name: 'Centurion',
        kind: ShipKind.CV,
        size: 4,
        exploration: 6,
        cargo: 1,
        combat: 8,
        cost: 13,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'praetorians-proconsul',
        faction: Faction.Praetorians,
        name: 'Proconsul',
        kind: ShipKind.CV,
        size: 4,
        exploration: 3,
        cargo: 3,
        combat: 6,
        cost: 12,
        fast: true,
        mining: true,
        research: false
    },
    {
        id: 'praetorians-myrmidon',
        faction: Faction.Praetorians,
        name: 'Myrmidon',
        kind: ShipKind.CV,
        size: 5,
        exploration: 7,
        cargo: 1,
        combat: 9,
        cost: 14,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-aquila',
        faction: Faction.Praetorians,
        name: 'Aquila',
        kind: ShipKind.CV,
        size: 6,
        exploration: 9,
        cargo: 1,
        combat: 9,
        cost: 16,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-athena',
        faction: Faction.Praetorians,
        name: 'Athena',
        kind: ShipKind.CV,
        size: 6,
        exploration: 4,
        cargo: 4,
        combat: 7,
        cost: 16,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'praetorians-hercules',
        faction: Faction.Praetorians,
        name: 'Hercules',
        kind: ShipKind.CV,
        size: 7,
        exploration: 10,
        cargo: 1,
        combat: 10,
        cost: 18,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-elysium',
        faction: Faction.Praetorians,
        name: 'Elysium',
        kind: ShipKind.CV,
        size: 8,
        exploration: 6,
        cargo: 5,
        combat: 8,
        cost: 20,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-praetor',
        faction: Faction.Praetorians,
        name: 'Praetor',
        kind: ShipKind.CV,
        size: 9,
        exploration: 12,
        cargo: 0,
        combat: 16,
        cost: 22,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'praetorians-imperator',
        faction: Faction.Praetorians,
        name: 'Imperator',
        kind: ShipKind.CV,
        size: 10,
        exploration: 12,
        cargo: 4,
        combat: 20,
        cost: 29,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-copernicus',
        faction: Faction.Starfarers,
        name: 'Copernicus',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-kepler',
        faction: Faction.Starfarers,
        name: 'Kepler',
        kind: ShipKind.RE,
        size: 0,
        exploration: 3,
        cargo: 0,
        combat: 0,
        cost: 5,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-kuiper',
        faction: Faction.Starfarers,
        name: 'Kuiper',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-messier',
        faction: Faction.Starfarers,
        name: 'Messier',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-andromeda',
        faction: Faction.Starfarers,
        name: 'Andromeda',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 2,
        combat: 0,
        cost: 7,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'starfarers-orion',
        faction: Faction.Starfarers,
        name: 'Orion',
        kind: ShipKind.CV,
        size: 2,
        exploration: 5,
        cargo: 0,
        combat: 3,
        cost: 7,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'starfarers-discovery',
        faction: Faction.Starfarers,
        name: 'Discovery',
        kind: ShipKind.CV,
        size: 3,
        exploration: 5,
        cargo: 1,
        combat: 5,
        cost: 10,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-pytheas',
        faction: Faction.Starfarers,
        name: 'Pytheas',
        kind: ShipKind.CV,
        size: 3,
        exploration: 4,
        cargo: 2,
        combat: 2,
        cost: 9,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'starfarers-proxima',
        faction: Faction.Starfarers,
        name: 'Proxima',
        kind: ShipKind.CV,
        size: 4,
        exploration: 6,
        cargo: 0,
        combat: 5,
        cost: 10,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-stargazer',
        faction: Faction.Starfarers,
        name: 'Stargazer',
        kind: ShipKind.CV,
        size: 4,
        exploration: 3,
        cargo: 3,
        combat: 3,
        cost: 11,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-polaris',
        faction: Faction.Starfarers,
        name: 'Polaris',
        kind: ShipKind.CV,
        size: 5,
        exploration: 3,
        cargo: 4,
        combat: 3,
        cost: 12,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'starfarers-voyager',
        faction: Faction.Starfarers,
        name: 'Voyager',
        kind: ShipKind.CV,
        size: 5,
        exploration: 7,
        cargo: 1,
        combat: 7,
        cost: 13,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-nova',
        faction: Faction.Starfarers,
        name: 'Nova',
        kind: ShipKind.CV,
        size: 6,
        exploration: 8,
        cargo: 2,
        combat: 9,
        cost: 17,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-comet',
        faction: Faction.Starfarers,
        name: 'Comet',
        kind: ShipKind.CV,
        size: 7,
        exploration: 10,
        cargo: 1,
        combat: 12,
        cost: 19,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'starfarers-constellation',
        faction: Faction.Starfarers,
        name: 'Constellation',
        kind: ShipKind.CV,
        size: 7,
        exploration: 10,
        cargo: 1,
        combat: 12,
        cost: 19,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'starfarers-starfury',
        faction: Faction.Starfarers,
        name: 'Starfury',
        kind: ShipKind.CV,
        size: 9,
        exploration: 12,
        cargo: 2,
        combat: 16,
        cost: 24,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'starfarers-galactica',
        faction: Faction.Starfarers,
        name: 'Galactica',
        kind: ShipKind.CV,
        size: 10,
        exploration: 12,
        cargo: 3,
        combat: 18,
        cost: 27,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-harbinger',
        faction: Faction.Syndicate,
        name: 'Harbinger',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-nomad',
        faction: Faction.Syndicate,
        name: 'Nomad',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-vagabond',
        faction: Faction.Syndicate,
        name: 'Vagabond',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-cobra',
        faction: Faction.Syndicate,
        name: 'Cobra',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 1,
        combat: 3,
        cost: 7,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-python',
        faction: Faction.Syndicate,
        name: 'Python',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 1,
        combat: 3,
        cost: 7,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'syndicate-viper',
        faction: Faction.Syndicate,
        name: 'Viper',
        kind: ShipKind.CV,
        size: 2,
        exploration: 2,
        cargo: 1,
        combat: 4,
        cost: 6,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-serpent',
        faction: Faction.Syndicate,
        name: 'Serpent',
        kind: ShipKind.CV,
        size: 3,
        exploration: 4,
        cargo: 1,
        combat: 4,
        cost: 8,
        fast: false,
        mining: false,
        research: true
    },
    {
        id: 'syndicate-sisyphus',
        faction: Faction.Syndicate,
        name: 'Sisyphus',
        kind: ShipKind.CV,
        size: 3,
        exploration: 2,
        cargo: 2,
        combat: 3,
        cost: 8,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'syndicate-corsair',
        faction: Faction.Syndicate,
        name: 'Corsair',
        kind: ShipKind.CV,
        size: 4,
        exploration: 5,
        cargo: 2,
        combat: 5,
        cost: 12,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-marauder',
        faction: Faction.Syndicate,
        name: 'Marauder',
        kind: ShipKind.CV,
        size: 5,
        exploration: 6,
        cargo: 1,
        combat: 6,
        cost: 12,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-relentless',
        faction: Faction.Syndicate,
        name: 'Relentless',
        kind: ShipKind.CV,
        size: 5,
        exploration: 3,
        cargo: 3,
        combat: 4,
        cost: 11,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-reaver',
        faction: Faction.Syndicate,
        name: 'Reaver',
        kind: ShipKind.CV,
        size: 6,
        exploration: 6,
        cargo: 2,
        combat: 8,
        cost: 14,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-scavenger',
        faction: Faction.Syndicate,
        name: 'Scavenger',
        kind: ShipKind.CV,
        size: 6,
        exploration: 3,
        cargo: 3,
        combat: 7,
        cost: 13,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'syndicate-antagonist',
        faction: Faction.Syndicate,
        name: 'Antagonist',
        kind: ShipKind.CV,
        size: 7,
        exploration: 6,
        cargo: 1,
        combat: 10,
        cost: 15,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-insurgent',
        faction: Faction.Syndicate,
        name: 'Insurgent',
        kind: ShipKind.CV,
        size: 7,
        exploration: 6,
        cargo: 1,
        combat: 10,
        cost: 15,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-nemesis',
        faction: Faction.Syndicate,
        name: 'Nemesis',
        kind: ShipKind.CV,
        size: 7,
        exploration: 7,
        cargo: 3,
        combat: 12,
        cost: 19,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'syndicate-dreadnought',
        faction: Faction.Syndicate,
        name: 'Dreadnought',
        kind: ShipKind.CV,
        size: 8,
        exploration: 8,
        cargo: 3,
        combat: 16,
        cost: 22,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-franklin',
        faction: Faction.Transhumanists,
        name: 'Franklin',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-curie',
        faction: Faction.Transhumanists,
        name: 'Curie',
        kind: ShipKind.RE,
        size: 0,
        exploration: 3,
        cargo: 0,
        combat: 0,
        cost: 5,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-hawking',
        faction: Faction.Transhumanists,
        name: 'Hawking',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-foucault',
        faction: Faction.Transhumanists,
        name: 'Foucault',
        kind: ShipKind.RE,
        size: 0,
        exploration: 2,
        cargo: 0,
        combat: 0,
        cost: 4,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-daedalus',
        faction: Faction.Transhumanists,
        name: 'Daedalus',
        kind: ShipKind.CV,
        size: 2,
        exploration: 4,
        cargo: 1,
        combat: 0,
        cost: 7,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'transhumanists-icarus',
        faction: Faction.Transhumanists,
        name: 'Icarus',
        kind: ShipKind.CV,
        size: 3,
        exploration: 5,
        cargo: 0,
        combat: 5,
        cost: 8,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-perdix',
        faction: Faction.Transhumanists,
        name: 'Perdix',
        kind: ShipKind.CV,
        size: 3,
        exploration: 3,
        cargo: 3,
        combat: 0,
        cost: 9,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'transhumanists-centaur',
        faction: Faction.Transhumanists,
        name: 'Centaur',
        kind: ShipKind.CV,
        size: 4,
        exploration: 5,
        cargo: 0,
        combat: 7,
        cost: 10,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'transhumanists-vulcan',
        faction: Faction.Transhumanists,
        name: 'Vulcan',
        kind: ShipKind.CV,
        size: 4,
        exploration: 3,
        cargo: 3,
        combat: 4,
        cost: 11,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'transhumanists-archimedes',
        faction: Faction.Transhumanists,
        name: 'Archimedes',
        kind: ShipKind.CV,
        size: 5,
        exploration: 4,
        cargo: 4,
        combat: 2,
        cost: 13,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'transhumanists-griffin',
        faction: Faction.Transhumanists,
        name: 'Griffin',
        kind: ShipKind.CV,
        size: 5,
        exploration: 6,
        cargo: 0,
        combat: 8,
        cost: 12,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'transhumanists-eratosthenes',
        faction: Faction.Transhumanists,
        name: 'Eratosthenes',
        kind: ShipKind.CV,
        size: 6,
        exploration: 5,
        cargo: 3,
        combat: 6,
        cost: 15,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'transhumanists-pegasus',
        faction: Faction.Transhumanists,
        name: 'Pegasus',
        kind: ShipKind.CV,
        size: 6,
        exploration: 7,
        cargo: 1,
        combat: 10,
        cost: 16,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'transhumanists-da-vinci',
        faction: Faction.Transhumanists,
        name: 'Da Vinci',
        kind: ShipKind.CV,
        size: 7,
        exploration: 3,
        cargo: 5,
        combat: 8,
        cost: 17,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'transhumanists-chimera',
        faction: Faction.Transhumanists,
        name: 'Chimera',
        kind: ShipKind.CV,
        size: 8,
        exploration: 8,
        cargo: 0,
        combat: 14,
        cost: 17,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-minotaur',
        faction: Faction.Transhumanists,
        name: 'Minotaur',
        kind: ShipKind.CV,
        size: 8,
        exploration: 8,
        cargo: 0,
        combat: 14,
        cost: 17,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'transhumanists-prometheus',
        faction: Faction.Transhumanists,
        name: 'Prometheus',
        kind: ShipKind.CV,
        size: 10,
        exploration: 9,
        cargo: 4,
        combat: 18,
        cost: 26,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'truepath-faithful',
        faction: Faction.TruePath,
        name: 'Faithful',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-lightbringer',
        faction: Faction.TruePath,
        name: 'Lightbringer',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-pathfinder',
        faction: Faction.TruePath,
        name: 'Pathfinder',
        kind: ShipKind.RE,
        size: 0,
        exploration: 1,
        cargo: 0,
        combat: 0,
        cost: 3,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-ardent-spirit',
        faction: Faction.TruePath,
        name: 'Ardent Spirit',
        kind: ShipKind.CV,
        size: 2,
        exploration: 3,
        cargo: 1,
        combat: 0,
        cost: 6,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'truepath-firebrand',
        faction: Faction.TruePath,
        name: 'Firebrand',
        kind: ShipKind.CV,
        size: 2,
        exploration: 2,
        cargo: 0,
        combat: 4,
        cost: 5,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'truepath-pilgrim',
        faction: Faction.TruePath,
        name: 'Pilgrim',
        kind: ShipKind.CV,
        size: 2,
        exploration: 2,
        cargo: 2,
        combat: 1,
        cost: 7,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'truepath-oathkeeper',
        faction: Faction.TruePath,
        name: 'Oathkeeper',
        kind: ShipKind.CV,
        size: 3,
        exploration: 3,
        cargo: 0,
        combat: 6,
        cost: 8,
        fast: true,
        mining: false,
        research: true
    },
    {
        id: 'truepath-rising-star',
        faction: Faction.TruePath,
        name: 'Rising Star',
        kind: ShipKind.CV,
        size: 3,
        exploration: 3,
        cargo: 3,
        combat: 0,
        cost: 9,
        fast: false,
        mining: true,
        research: false
    },
    {
        id: 'truepath-celestial-ark',
        faction: Faction.TruePath,
        name: 'Celestial Ark',
        kind: ShipKind.CV,
        size: 4,
        exploration: 3,
        cargo: 3,
        combat: 6,
        cost: 11,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-paladin',
        faction: Faction.TruePath,
        name: 'Paladin',
        kind: ShipKind.CV,
        size: 5,
        exploration: 5,
        cargo: 1,
        combat: 7,
        cost: 11,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-proselyte',
        faction: Faction.TruePath,
        name: 'Proselyte',
        kind: ShipKind.CV,
        size: 5,
        exploration: 4,
        cargo: 1,
        combat: 7,
        cost: 10,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-unity',
        faction: Faction.TruePath,
        name: 'Unity',
        kind: ShipKind.CV,
        size: 5,
        exploration: 4,
        cargo: 2,
        combat: 5,
        cost: 11,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-ascendance',
        faction: Faction.TruePath,
        name: 'Ascendance',
        kind: ShipKind.CV,
        size: 6,
        exploration: 3,
        cargo: 4,
        combat: 4,
        cost: 14,
        fast: false,
        mining: true,
        research: true
    },
    {
        id: 'truepath-guardian',
        faction: Faction.TruePath,
        name: 'Guardian',
        kind: ShipKind.CV,
        size: 6,
        exploration: 6,
        cargo: 0,
        combat: 8,
        cost: 12,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-eternal-flame',
        faction: Faction.TruePath,
        name: 'Eternal Flame',
        kind: ShipKind.CV,
        size: 7,
        exploration: 7,
        cargo: 1,
        combat: 12,
        cost: 17,
        fast: true,
        mining: false,
        research: false
    },
    {
        id: 'truepath-intercessor',
        faction: Faction.TruePath,
        name: 'Intercessor',
        kind: ShipKind.CV,
        size: 8,
        exploration: 8,
        cargo: 2,
        combat: 15,
        cost: 20,
        fast: false,
        mining: false,
        research: false
    },
    {
        id: 'truepath-revenant',
        faction: Faction.TruePath,
        name: 'Revenant',
        kind: ShipKind.CV,
        size: 9,
        exploration: 9,
        cargo: 2,
        combat: 16,
        cost: 22,
        fast: true,
        mining: false,
        research: false
    }
]
