// Generated by scripts/import-art.mjs from the Stellar Horizons II Vassal module.
import art0 from '$lib/images/art/systems/sol.webp'
import art1 from '$lib/images/art/systems/v2306-ophiuchi.webp'
import art2 from '$lib/images/art/systems/barnards-star.webp'
import art3 from '$lib/images/art/systems/wise-0855-0714.webp'
import art4 from '$lib/images/art/systems/procyon.webp'
import art5 from '$lib/images/art/systems/gliese-876.webp'
import art6 from '$lib/images/art/systems/luhman-16.webp'
import art7 from '$lib/images/art/systems/alpha-centauri.webp'
import art8 from '$lib/images/art/systems/sirius.webp'
import art9 from '$lib/images/art/ships/consortium-prospector.webp'
import art10 from '$lib/images/art/ships/consortium-prosperity.webp'
import art11 from '$lib/images/art/ships/consortium-surveyor.webp'
import art12 from '$lib/images/art/ships/consortium-guildmaster.webp'
import art13 from '$lib/images/art/ships/consortium-nostromo.webp'
import art14 from '$lib/images/art/ships/consortium-sapphire.webp'
import art15 from '$lib/images/art/ships/consortium-opal-star.webp'
import art16 from '$lib/images/art/ships/consortium-desire.webp'
import art17 from '$lib/images/art/ships/consortium-destiny.webp'
import art18 from '$lib/images/art/ships/consortium-enterprise.webp'
import art19 from '$lib/images/art/ships/consortium-majestic.webp'
import art20 from '$lib/images/art/ships/consortium-zephyr.webp'
import art21 from '$lib/images/art/ships/consortium-aquarius.webp'
import art22 from '$lib/images/art/ships/consortium-empress.webp'
import art23 from '$lib/images/art/ships/consortium-trident.webp'
import art24 from '$lib/images/art/ships/consortium-neptune.webp'
import art25 from '$lib/images/art/ships/consortium-colossus.webp'
import art26 from '$lib/images/art/ships/givers-linnaeus.webp'
import art27 from '$lib/images/art/ships/givers-humboldt.webp'
import art28 from '$lib/images/art/ships/givers-mendel.webp'
import art29 from '$lib/images/art/ships/givers-bougainville.webp'
import art30 from '$lib/images/art/ships/givers-darwin.webp'
import art31 from '$lib/images/art/ships/givers-mirabilis.webp'
import art32 from '$lib/images/art/ships/givers-serenity.webp'
import art33 from '$lib/images/art/ships/givers-tempest.webp'
import art34 from '$lib/images/art/ships/givers-osanyin.webp'
import art35 from '$lib/images/art/ships/givers-viridis.webp'
import art36 from '$lib/images/art/ships/givers-eden.webp'
import art37 from '$lib/images/art/ships/givers-typhoon.webp'
import art38 from '$lib/images/art/ships/givers-artemis.webp'
import art39 from '$lib/images/art/ships/givers-eclipse.webp'
import art40 from '$lib/images/art/ships/givers-boreas.webp'
import art41 from '$lib/images/art/ships/givers-helios.webp'
import art42 from '$lib/images/art/ships/givers-gaia.webp'
import art43 from '$lib/images/art/ships/praetorians-audax.webp'
import art44 from '$lib/images/art/ships/praetorians-fidelis.webp'
import art45 from '$lib/images/art/ships/praetorians-peregrinus.webp'
import art46 from '$lib/images/art/ships/praetorians-noctua.webp'
import art47 from '$lib/images/art/ships/praetorians-odyssey.webp'
import art48 from '$lib/images/art/ships/praetorians-argonaut.webp'
import art49 from '$lib/images/art/ships/praetorians-gladiator.webp'
import art50 from '$lib/images/art/ships/praetorians-centurion.webp'
import art51 from '$lib/images/art/ships/praetorians-proconsul.webp'
import art52 from '$lib/images/art/ships/praetorians-myrmidon.webp'
import art53 from '$lib/images/art/ships/praetorians-aquila.webp'
import art54 from '$lib/images/art/ships/praetorians-athena.webp'
import art55 from '$lib/images/art/ships/praetorians-hercules.webp'
import art56 from '$lib/images/art/ships/praetorians-elysium.webp'
import art57 from '$lib/images/art/ships/praetorians-praetor.webp'
import art58 from '$lib/images/art/ships/praetorians-imperator.webp'
import art59 from '$lib/images/art/ships/starfarers-copernicus.webp'
import art60 from '$lib/images/art/ships/starfarers-kepler.webp'
import art61 from '$lib/images/art/ships/starfarers-kuiper.webp'
import art62 from '$lib/images/art/ships/starfarers-messier.webp'
import art63 from '$lib/images/art/ships/starfarers-andromeda.webp'
import art64 from '$lib/images/art/ships/starfarers-orion.webp'
import art65 from '$lib/images/art/ships/starfarers-discovery.webp'
import art66 from '$lib/images/art/ships/starfarers-pytheas.webp'
import art67 from '$lib/images/art/ships/starfarers-proxima.webp'
import art68 from '$lib/images/art/ships/starfarers-stargazer.webp'
import art69 from '$lib/images/art/ships/starfarers-polaris.webp'
import art70 from '$lib/images/art/ships/starfarers-voyager.webp'
import art71 from '$lib/images/art/ships/starfarers-nova.webp'
import art72 from '$lib/images/art/ships/starfarers-comet.webp'
import art73 from '$lib/images/art/ships/starfarers-constellation.webp'
import art74 from '$lib/images/art/ships/starfarers-starfury.webp'
import art75 from '$lib/images/art/ships/starfarers-galactica.webp'
import art76 from '$lib/images/art/ships/syndicate-harbinger.webp'
import art77 from '$lib/images/art/ships/syndicate-nomad.webp'
import art78 from '$lib/images/art/ships/syndicate-vagabond.webp'
import art79 from '$lib/images/art/ships/syndicate-cobra.webp'
import art80 from '$lib/images/art/ships/syndicate-python.webp'
import art81 from '$lib/images/art/ships/syndicate-viper.webp'
import art82 from '$lib/images/art/ships/syndicate-serpent.webp'
import art83 from '$lib/images/art/ships/syndicate-sisyphus.webp'
import art84 from '$lib/images/art/ships/syndicate-corsair.webp'
import art85 from '$lib/images/art/ships/syndicate-marauder.webp'
import art86 from '$lib/images/art/ships/syndicate-relentless.webp'
import art87 from '$lib/images/art/ships/syndicate-reaver.webp'
import art88 from '$lib/images/art/ships/syndicate-scavenger.webp'
import art89 from '$lib/images/art/ships/syndicate-antagonist.webp'
import art90 from '$lib/images/art/ships/syndicate-insurgent.webp'
import art91 from '$lib/images/art/ships/syndicate-nemesis.webp'
import art92 from '$lib/images/art/ships/syndicate-dreadnought.webp'
import art93 from '$lib/images/art/ships/transhumanists-franklin.webp'
import art94 from '$lib/images/art/ships/transhumanists-curie.webp'
import art95 from '$lib/images/art/ships/transhumanists-hawking.webp'
import art96 from '$lib/images/art/ships/transhumanists-foucault.webp'
import art97 from '$lib/images/art/ships/transhumanists-daedalus.webp'
import art98 from '$lib/images/art/ships/transhumanists-icarus.webp'
import art99 from '$lib/images/art/ships/transhumanists-perdix.webp'
import art100 from '$lib/images/art/ships/transhumanists-centaur.webp'
import art101 from '$lib/images/art/ships/transhumanists-vulcan.webp'
import art102 from '$lib/images/art/ships/transhumanists-archimedes.webp'
import art103 from '$lib/images/art/ships/transhumanists-griffin.webp'
import art104 from '$lib/images/art/ships/transhumanists-eratosthenes.webp'
import art105 from '$lib/images/art/ships/transhumanists-pegasus.webp'
import art106 from '$lib/images/art/ships/transhumanists-da-vinci.webp'
import art107 from '$lib/images/art/ships/transhumanists-chimera.webp'
import art108 from '$lib/images/art/ships/transhumanists-minotaur.webp'
import art109 from '$lib/images/art/ships/transhumanists-prometheus.webp'
import art110 from '$lib/images/art/ships/truepath-faithful.webp'
import art111 from '$lib/images/art/ships/truepath-lightbringer.webp'
import art112 from '$lib/images/art/ships/truepath-pathfinder.webp'
import art113 from '$lib/images/art/ships/truepath-ardent-spirit.webp'
import art114 from '$lib/images/art/ships/truepath-firebrand.webp'
import art115 from '$lib/images/art/ships/truepath-pilgrim.webp'
import art116 from '$lib/images/art/ships/truepath-oathkeeper.webp'
import art117 from '$lib/images/art/ships/truepath-rising-star.webp'
import art118 from '$lib/images/art/ships/truepath-celestial-ark.webp'
import art119 from '$lib/images/art/ships/truepath-paladin.webp'
import art120 from '$lib/images/art/ships/truepath-proselyte.webp'
import art121 from '$lib/images/art/ships/truepath-unity.webp'
import art122 from '$lib/images/art/ships/truepath-ascendance.webp'
import art123 from '$lib/images/art/ships/truepath-guardian.webp'
import art124 from '$lib/images/art/ships/truepath-eternal-flame.webp'
import art125 from '$lib/images/art/ships/truepath-intercessor.webp'
import art126 from '$lib/images/art/ships/truepath-revenant.webp'
import art127 from '$lib/images/art/worlds/Planet-M-25-2-4.webp'
import art128 from '$lib/images/art/worlds/Planet-M-27-2-5-b.webp'
import art129 from '$lib/images/art/worlds/Planet-M-25-2-4-b.webp'
import art130 from '$lib/images/art/worlds/Planet-M-25-3-5.webp'
import art131 from '$lib/images/art/worlds/Planet-M-25-3-5-b.webp'
import art132 from '$lib/images/art/worlds/Planet-M-26-3-5-b.webp'
import art133 from '$lib/images/art/worlds/Planet-M-26-2-4.webp'
import art134 from '$lib/images/art/worlds/Planet-M-29-2-5-b.webp'
import art135 from '$lib/images/art/worlds/Planet-M-26-2-6.webp'
import art136 from '$lib/images/art/worlds/Planet-M-26-2-6-b.webp'
import art137 from '$lib/images/art/worlds/Planet-M-26-3-4.webp'
import art138 from '$lib/images/art/worlds/Planet-M-27-3-5-b.webp'
import art139 from '$lib/images/art/worlds/Planet-M-26-3-5.webp'
import art140 from '$lib/images/art/worlds/Planet-M-26-3-6.webp'
import art141 from '$lib/images/art/worlds/Planet-M-26-3-6-b.webp'
import art142 from '$lib/images/art/worlds/Planet-M-27-3-7-b.webp'
import art143 from '$lib/images/art/worlds/Planet-M-27-2-4.webp'
import art144 from '$lib/images/art/worlds/Planet-M-27-2-6.webp'
import art145 from '$lib/images/art/worlds/Planet-M-27-3-5.webp'
import art146 from '$lib/images/art/worlds/Planet-M-29-3-7-b.webp'
import art147 from '$lib/images/art/worlds/Planet-O-17-3-4.webp'
import art148 from '$lib/images/art/worlds/Planet-O-20-2-2-b.webp'
import art149 from '$lib/images/art/worlds/Planet-O-18-2-2.webp'
import art150 from '$lib/images/art/worlds/Planet-O-20-2-2a-b.webp'
import art151 from '$lib/images/art/worlds/Planet-O-19-3-3.webp'
import art152 from '$lib/images/art/worlds/Planet-O-22-4-3-b.webp'
import art153 from '$lib/images/art/worlds/Planet-O-19-4-4.webp'
import art154 from '$lib/images/art/worlds/Planet-O-23-4-5-b.webp'
import art155 from '$lib/images/art/worlds/Planet-O-20-1-2.webp'
import art156 from '$lib/images/art/worlds/Planet-O-20-1-2-b.webp'
import art157 from '$lib/images/art/worlds/Planet-O-20-1-3.webp'
import art158 from '$lib/images/art/worlds/Planet-O-20-1-3-b.webp'
import art159 from '$lib/images/art/worlds/Planet-O-20-2-2.webp'
import art160 from '$lib/images/art/worlds/Planet-O-20-3-3.webp'
import art161 from '$lib/images/art/worlds/Planet-O-21-3-4-b.webp'
import art162 from '$lib/images/art/worlds/Planet-O-21-2-3.webp'
import art163 from '$lib/images/art/worlds/Planet-O-20-3-5-b.webp'
import art164 from '$lib/images/art/worlds/Planet-O-21-3-3.webp'
import art165 from '$lib/images/art/worlds/Planet-O-21-3-3-b.webp'
import art166 from '$lib/images/art/worlds/Planet-O-22-2-3.webp'
import art167 from '$lib/images/art/worlds/Planet-L-16-1-3.webp'
import art168 from '$lib/images/art/worlds/Planet-L-18-2-4a-b.webp'
import art169 from '$lib/images/art/worlds/Planet-L-16-1-4.webp'
import art170 from '$lib/images/art/worlds/Planet-L-18-2-4-b.webp'
import art171 from '$lib/images/art/worlds/Planet-L-18-2-5-b.webp'
import art172 from '$lib/images/art/worlds/Planet-L-16-2-4.webp'
import art173 from '$lib/images/art/worlds/Planet-L-16-2-5.webp'
import art174 from '$lib/images/art/worlds/Planet-L-16-2-5-b.webp'
import art175 from '$lib/images/art/worlds/Planet-L-17-1-4.webp'
import art176 from '$lib/images/art/worlds/Planet-L-17-1-4-b.webp'
import art177 from '$lib/images/art/worlds/Planet-L-17-2-5.webp'
import art178 from '$lib/images/art/worlds/Planet-L-17-2-5-b.webp'
import art179 from '$lib/images/art/worlds/Planet-L-17-3-6.webp'
import art180 from '$lib/images/art/worlds/Planet-L-17-3-6-b.webp'
import art181 from '$lib/images/art/worlds/Planet-L-18-1-3.webp'
import art182 from '$lib/images/art/worlds/Planet-L-20-2-4-b.webp'
import art183 from '$lib/images/art/worlds/Planet-L-18-2-4.webp'
import art184 from '$lib/images/art/worlds/Planet-L-18-2-5.webp'
import art185 from '$lib/images/art/worlds/Planet-L-20-3-6-b.webp'
import art186 from '$lib/images/art/worlds/Planet-L-18-3-6.webp'
import art187 from '$lib/images/art/worlds/Planet-L-20-4-7-b.webp'
import art188 from '$lib/images/art/worlds/Planet-H-13-2-4.webp'
import art189 from '$lib/images/art/worlds/Planet-H-13-2-4-b.webp'
import art190 from '$lib/images/art/worlds/Planet-H-13-2-5.webp'
import art191 from '$lib/images/art/worlds/Planet-H-13-2-5-b.webp'
import art192 from '$lib/images/art/worlds/Planet-H-13-3-5.webp'
import art193 from '$lib/images/art/worlds/Planet-H-13-3-5-b.webp'
import art194 from '$lib/images/art/worlds/Planet-H-14-1-3.webp'
import art195 from '$lib/images/art/worlds/Planet-H-14-1-3-b.webp'
import art196 from '$lib/images/art/worlds/Planet-H-14-2-4.webp'
import art197 from '$lib/images/art/worlds/Planet-H-14-2-4-b.webp'
import art198 from '$lib/images/art/worlds/Planet-H-14-2-5.webp'
import art199 from '$lib/images/art/worlds/Planet-H-14-2-5-b.webp'
import art200 from '$lib/images/art/worlds/Planet-H-14-3-6.webp'
import art201 from '$lib/images/art/worlds/Planet-H-15-3-7-b.webp'
import art202 from '$lib/images/art/worlds/Planet-P-10-2-1.webp'
import art203 from '$lib/images/art/worlds/Planet-P-11-2-3-b.webp'
import art204 from '$lib/images/art/worlds/Planet-P-11-2-2.webp'
import art205 from '$lib/images/art/worlds/Planet-P-11-2-2-b.webp'
import art206 from '$lib/images/art/worlds/Planet-P-11-3-2.webp'
import art207 from '$lib/images/art/worlds/Planet-P-12-4-4-b.webp'
import art208 from '$lib/images/art/worlds/Planet-P-11-3-3.webp'
import art209 from '$lib/images/art/worlds/Planet-P-11-3-3-b.webp'
import art210 from '$lib/images/art/worlds/Planet-P-11-3-4.webp'
import art211 from '$lib/images/art/worlds/Planet-P-11-3-4-b.webp'
import art212 from '$lib/images/art/worlds/Planet-P-12-1-1.webp'
import art213 from '$lib/images/art/worlds/Planet-P-12-1-1-b.webp'
import art214 from '$lib/images/art/worlds/Planet-P-12-2-2.webp'
import art215 from '$lib/images/art/worlds/Planet-P-12-2-2-b.webp'
import art216 from '$lib/images/art/worlds/Planet-P-12-3-2.webp'
import art217 from '$lib/images/art/worlds/Planet-P-12-3-3-b.webp'
import art218 from '$lib/images/art/worlds/Planet-P-12-3-3.webp'
import art219 from '$lib/images/art/worlds/Planet-P-9-1-1.webp'
import art220 from '$lib/images/art/worlds/Planet-P-10-2-2-b.webp'
import art221 from '$lib/images/art/worlds/Planet-K-5-1-1.webp'
import art222 from '$lib/images/art/worlds/Planet-K-5-1-1-b.webp'
import art223 from '$lib/images/art/worlds/Planet-K-6-1-1.webp'
import art224 from '$lib/images/art/worlds/Planet-K-8-1-3-b.webp'
import art225 from '$lib/images/art/worlds/Planet-K-6-1-2.webp'
import art226 from '$lib/images/art/worlds/Planet-K-6-2-2.webp'
import art227 from '$lib/images/art/worlds/Planet-K-6-2-3.webp'
import art228 from '$lib/images/art/worlds/Planet-K-8-2-4-b.webp'
import art229 from '$lib/images/art/worlds/Planet-K-7-1-2.webp'
import art230 from '$lib/images/art/worlds/Planet-K-9-1-3-b.webp'
import art231 from '$lib/images/art/worlds/Planet-K-7-1-3.webp'
import art232 from '$lib/images/art/worlds/Planet-K-7-1-3-b.webp'
import art233 from '$lib/images/art/worlds/Planet-K-7-2-3.webp'
import art234 from '$lib/images/art/worlds/Planet-K-7-2-3-b.webp'
import art235 from '$lib/images/art/worlds/Planet-K-7-3-3.webp'
import art236 from '$lib/images/art/worlds/Planet-K-7-3-3-b.webp'
import art237 from '$lib/images/art/worlds/Planet-K-7-3-4.webp'
import art238 from '$lib/images/art/worlds/Planet-K-7-3-4-b.webp'
import art239 from '$lib/images/art/worlds/Planet-K-7-4-4.webp'
import art240 from '$lib/images/art/worlds/Planet-K-7-4-4-b.webp'
import art241 from '$lib/images/art/worlds/Planet-K-8-1-2.webp'
import art242 from '$lib/images/art/worlds/Planet-K-10-1-4-b.webp'
import art243 from '$lib/images/art/worlds/Planet-K-8-2-3.webp'
import art244 from '$lib/images/art/worlds/Planet-K-10-2-5-b.webp'
import art245 from '$lib/images/art/worlds/Planet-K-8-2-4.webp'
import art246 from '$lib/images/art/worlds/Planet-K-8-32-4.webp'
import art247 from '$lib/images/art/worlds/Planet-K-10-3-5-b.webp'
import art248 from '$lib/images/art/worlds/Planet-K-9-3-2.webp'
import art249 from '$lib/images/art/worlds/Planet-K-10-3-4-b.webp'
import art250 from '$lib/images/art/worlds/Planet-A-4-2-5.webp'
import art251 from '$lib/images/art/worlds/Planet-A-4-2-5-b.webp'
import art252 from '$lib/images/art/worlds/Planet-A-5-3-5.webp'
import art253 from '$lib/images/art/worlds/Planet-A-6-3-6-b.webp'
import art254 from '$lib/images/art/worlds/Planet-A-5-3-7.webp'
import art255 from '$lib/images/art/worlds/Planet-A-6-3-9-b.webp'
import art256 from '$lib/images/art/worlds/Planet-A-5-4-6.webp'
import art257 from '$lib/images/art/worlds/Planet-A-6-4-9-b.webp'
import art258 from '$lib/images/art/worlds/Planet-A-6-2-6.webp'
import art259 from '$lib/images/art/worlds/Planet-A-7-2-9-b.webp'
import art260 from '$lib/images/art/worlds/Planet-A-6-3-7.webp'
import art261 from '$lib/images/art/worlds/Planet-A-7-3-9-b.webp'
import art262 from '$lib/images/art/worlds/Planet-A-6-4-7.webp'
import art263 from '$lib/images/art/worlds/Planet-A-7-4-9-b.webp'
import art264 from '$lib/images/art/worlds/Planet-A-6-4-8.webp'
import art265 from '$lib/images/art/worlds/J-4-3-4-2.webp'
import art266 from '$lib/images/art/worlds/Planet-J-8-3-8-b.webp'
import art267 from '$lib/images/art/worlds/Planet-J-8-4-8-2-b.webp'
import art268 from '$lib/images/art/worlds/Planet-J-1-1-1.webp'
import art269 from '$lib/images/art/worlds/Planet-J-3-2-3.webp'
import art270 from '$lib/images/art/worlds/Planet-J-1-1-1b.webp'
import art271 from '$lib/images/art/worlds/Planet-J-3-2-3b.webp'
import art272 from '$lib/images/art/worlds/Planet-J-1-1-2.webp'
import art273 from '$lib/images/art/worlds/Planet-J-1-1-2-b.webp'
import art274 from '$lib/images/art/worlds/Planet-J-10-3-8.webp'
import art275 from '$lib/images/art/worlds/Planet-J-10-3-8-b.webp'
import art276 from '$lib/images/art/worlds/Planet-J-2-2-2-2-.webp'
import art277 from '$lib/images/art/worlds/Planet-J-2-2-2-2-b.webp'
import art278 from '$lib/images/art/worlds/Planet-J-4-3-4.webp'
import art279 from '$lib/images/art/worlds/Planet-J-2-2-2.webp'
import art280 from '$lib/images/art/worlds/Planet-J-4-2-2-b.webp'
import art281 from '$lib/images/art/worlds/Planet-J-3-2-2.webp'
import art282 from '$lib/images/art/worlds/Planet-J-6-3-4-b.webp'
import art283 from '$lib/images/art/worlds/Planet-J-3-2-3-2-.webp'
import art284 from '$lib/images/art/worlds/Planet-J-6-3-6-b.webp'
import art285 from '$lib/images/art/worlds/Planet-J-6-3-6-2-b.webp'
import art286 from '$lib/images/art/worlds/Planet-J-4-3-3.webp'
import art287 from '$lib/images/art/worlds/Planet-J-8-2-7.webp'
import art288 from '$lib/images/art/worlds/Planet-J-8-2-7-b.webp'
import art289 from '$lib/images/art/worlds/Planet-D-1-1-4.webp'
import art290 from '$lib/images/art/worlds/Planet-D-1-1-4-b.webp'
import art291 from '$lib/images/art/worlds/Planet-D-1-2-4.webp'
import art292 from '$lib/images/art/worlds/Planet-D-1-2-4-b.webp'
import art293 from '$lib/images/art/worlds/Planet-D-2-2-5.webp'
import art294 from '$lib/images/art/worlds/Planet-D-4-2-6-b.webp'
import art295 from '$lib/images/art/worlds/Planet-D-2-3-5.webp'
import art296 from '$lib/images/art/worlds/Planet-D-2-3-5-b.webp'
import art297 from '$lib/images/art/worlds/Planet-D-2-3-6.webp'
import art298 from '$lib/images/art/worlds/Planet-D-3-3-7-b.webp'
import art299 from '$lib/images/art/worlds/Planet-D-2-4-6.webp'
import art300 from '$lib/images/art/worlds/Planet-D-3-4-7-b.webp'
import art301 from '$lib/images/art/worlds/Planet-D-3-2-7.webp'
import art302 from '$lib/images/art/worlds/Planet-D-5-2-8-b.webp'
import art303 from '$lib/images/art/worlds/Planet-D-3-3-8.webp'
import art304 from '$lib/images/art/worlds/Planet-D-5-3-9-b.webp'
import art305 from '$lib/images/art/worlds/Planet-D-3-4-8.webp'
import art306 from '$lib/images/art/worlds/Planet-D-5-4-9-b.webp'
import art307 from '$lib/images/art/worlds/Planet-E-10-2-4.webp'
import art308 from '$lib/images/art/worlds/Planet-E-15-2-5-b.webp'
import art309 from '$lib/images/art/worlds/Planet-E-12-3-5.webp'
import art310 from '$lib/images/art/worlds/Planet-E-12-3-5-b.webp'
import art311 from '$lib/images/art/worlds/Planet-E-14-2-5.webp'
import art312 from '$lib/images/art/worlds/Planet-E-14-2-5-b.webp'
import art313 from '$lib/images/art/worlds/Planet-E-16-3-6.webp'
import art314 from '$lib/images/art/worlds/Planet-E-16-3-6-b.webp'
import art315 from '$lib/images/art/worlds/Planet-E-8-2-4.webp'
import art316 from '$lib/images/art/worlds/Planet-E-12-3-4-b.webp'
import art317 from '$lib/images/art/worlds/Planet-No-World.webp'
import art318 from '$lib/images/art/factions/Consortium.webp'
import art319 from '$lib/images/art/markers/settlement-Consortium.webp'
import art320 from '$lib/images/art/factions/Givers.webp'
import art321 from '$lib/images/art/markers/settlement-Givers.webp'
import art322 from '$lib/images/art/factions/Praetorians.webp'
import art323 from '$lib/images/art/markers/settlement-Praetorians.webp'
import art324 from '$lib/images/art/factions/Starfarers.webp'
import art325 from '$lib/images/art/markers/settlement-Starfarers.webp'
import art326 from '$lib/images/art/factions/Syndicate.webp'
import art327 from '$lib/images/art/markers/settlement-Syndicate.webp'
import art328 from '$lib/images/art/factions/Transhumanists.webp'
import art329 from '$lib/images/art/markers/settlement-Transhumanists.webp'
import art330 from '$lib/images/art/factions/TruePath.webp'
import art331 from '$lib/images/art/markers/settlement-TruePath.webp'
import art332 from '$lib/images/art/markers/tech-Biology-1.webp'
import art333 from '$lib/images/art/markers/tech-Biology-2.webp'
import art334 from '$lib/images/art/markers/tech-Biology-3.webp'
import art335 from '$lib/images/art/markers/tech-Biology-4.webp'
import art336 from '$lib/images/art/markers/tech-Biology-5.webp'
import art337 from '$lib/images/art/markers/exploration-Biology.webp'
import art338 from '$lib/images/art/markers/tech-Physics-1.webp'
import art339 from '$lib/images/art/markers/tech-Physics-2.webp'
import art340 from '$lib/images/art/markers/tech-Physics-3.webp'
import art341 from '$lib/images/art/markers/tech-Physics-4.webp'
import art342 from '$lib/images/art/markers/tech-Physics-5.webp'
import art343 from '$lib/images/art/markers/exploration-Physics.webp'
import art344 from '$lib/images/art/markers/tech-Engineering-1.webp'
import art345 from '$lib/images/art/markers/tech-Engineering-2.webp'
import art346 from '$lib/images/art/markers/tech-Engineering-3.webp'
import art347 from '$lib/images/art/markers/tech-Engineering-4.webp'
import art348 from '$lib/images/art/markers/tech-Engineering-5.webp'
import art349 from '$lib/images/art/markers/exploration-Engineering.webp'
import techTree from '$lib/images/art/charts/tech-tree.webp'

export const SYSTEM_ART: Record<string, string> = {
    sol: art0,
    'v2306-ophiuchi': art1,
    'barnards-star': art2,
    'wise-0855-0714': art3,
    procyon: art4,
    'gliese-876': art5,
    'luhman-16': art6,
    'alpha-centauri': art7,
    sirius: art8
}

export const SYSTEM_GEOMETRY: Record<
    string,
    { width: number; height: number; slots: number[][]; marker: number[] | null }
> = {
    sol: { width: 1067, height: 928, slots: [], marker: null },
    'v2306-ophiuchi': {
        width: 1066,
        height: 930,
        slots: [
            [326, 506],
            [360, 246],
            [862, 516]
        ],
        marker: [733, 816]
    },
    'barnards-star': {
        width: 1066,
        height: 929,
        slots: [
            [766, 326],
            [260, 508]
        ],
        marker: [731, 820]
    },
    'wise-0855-0714': {
        width: 1067,
        height: 926,
        slots: [
            [232, 502],
            [804, 334]
        ],
        marker: [732, 817]
    },
    procyon: {
        width: 1068,
        height: 924,
        slots: [
            [270, 384],
            [808, 484]
        ],
        marker: [729, 816]
    },
    'gliese-876': {
        width: 1070,
        height: 926,
        slots: [
            [734, 534],
            [714, 254],
            [204, 474]
        ],
        marker: [735, 815]
    },
    'luhman-16': {
        width: 1064,
        height: 928,
        slots: [
            [742, 474],
            [298, 322]
        ],
        marker: [733, 815]
    },
    'alpha-centauri': {
        width: 1065,
        height: 933,
        slots: [
            [474, 274],
            [806, 498],
            [196, 492]
        ],
        marker: [732, 820]
    },
    sirius: {
        width: 1067,
        height: 926,
        slots: [
            [710, 358],
            [284, 356]
        ],
        marker: [734, 813]
    }
}

export const SHIP_ART: Record<string, string> = {
    'consortium-prospector': art9,
    'consortium-prosperity': art10,
    'consortium-surveyor': art11,
    'consortium-guildmaster': art12,
    'consortium-nostromo': art13,
    'consortium-sapphire': art14,
    'consortium-opal-star': art15,
    'consortium-desire': art16,
    'consortium-destiny': art17,
    'consortium-enterprise': art18,
    'consortium-majestic': art19,
    'consortium-zephyr': art20,
    'consortium-aquarius': art21,
    'consortium-empress': art22,
    'consortium-trident': art23,
    'consortium-neptune': art24,
    'consortium-colossus': art25,
    'givers-linnaeus': art26,
    'givers-humboldt': art27,
    'givers-mendel': art28,
    'givers-bougainville': art29,
    'givers-darwin': art30,
    'givers-mirabilis': art31,
    'givers-serenity': art32,
    'givers-tempest': art33,
    'givers-osanyin': art34,
    'givers-viridis': art35,
    'givers-eden': art36,
    'givers-typhoon': art37,
    'givers-artemis': art38,
    'givers-eclipse': art39,
    'givers-boreas': art40,
    'givers-helios': art41,
    'givers-gaia': art42,
    'praetorians-audax': art43,
    'praetorians-fidelis': art44,
    'praetorians-peregrinus': art45,
    'praetorians-noctua': art46,
    'praetorians-odyssey': art47,
    'praetorians-argonaut': art48,
    'praetorians-gladiator': art49,
    'praetorians-centurion': art50,
    'praetorians-proconsul': art51,
    'praetorians-myrmidon': art52,
    'praetorians-aquila': art53,
    'praetorians-athena': art54,
    'praetorians-hercules': art55,
    'praetorians-elysium': art56,
    'praetorians-praetor': art57,
    'praetorians-imperator': art58,
    'starfarers-copernicus': art59,
    'starfarers-kepler': art60,
    'starfarers-kuiper': art61,
    'starfarers-messier': art62,
    'starfarers-andromeda': art63,
    'starfarers-orion': art64,
    'starfarers-discovery': art65,
    'starfarers-pytheas': art66,
    'starfarers-proxima': art67,
    'starfarers-stargazer': art68,
    'starfarers-polaris': art69,
    'starfarers-voyager': art70,
    'starfarers-nova': art71,
    'starfarers-comet': art72,
    'starfarers-constellation': art73,
    'starfarers-starfury': art74,
    'starfarers-galactica': art75,
    'syndicate-harbinger': art76,
    'syndicate-nomad': art77,
    'syndicate-vagabond': art78,
    'syndicate-cobra': art79,
    'syndicate-python': art80,
    'syndicate-viper': art81,
    'syndicate-serpent': art82,
    'syndicate-sisyphus': art83,
    'syndicate-corsair': art84,
    'syndicate-marauder': art85,
    'syndicate-relentless': art86,
    'syndicate-reaver': art87,
    'syndicate-scavenger': art88,
    'syndicate-antagonist': art89,
    'syndicate-insurgent': art90,
    'syndicate-nemesis': art91,
    'syndicate-dreadnought': art92,
    'transhumanists-franklin': art93,
    'transhumanists-curie': art94,
    'transhumanists-hawking': art95,
    'transhumanists-foucault': art96,
    'transhumanists-daedalus': art97,
    'transhumanists-icarus': art98,
    'transhumanists-perdix': art99,
    'transhumanists-centaur': art100,
    'transhumanists-vulcan': art101,
    'transhumanists-archimedes': art102,
    'transhumanists-griffin': art103,
    'transhumanists-eratosthenes': art104,
    'transhumanists-pegasus': art105,
    'transhumanists-da-vinci': art106,
    'transhumanists-chimera': art107,
    'transhumanists-minotaur': art108,
    'transhumanists-prometheus': art109,
    'truepath-faithful': art110,
    'truepath-lightbringer': art111,
    'truepath-pathfinder': art112,
    'truepath-ardent-spirit': art113,
    'truepath-firebrand': art114,
    'truepath-pilgrim': art115,
    'truepath-oathkeeper': art116,
    'truepath-rising-star': art117,
    'truepath-celestial-ark': art118,
    'truepath-paladin': art119,
    'truepath-proselyte': art120,
    'truepath-unity': art121,
    'truepath-ascendance': art122,
    'truepath-guardian': art123,
    'truepath-eternal-flame': art124,
    'truepath-intercessor': art125,
    'truepath-revenant': art126
}

export const WORLD_ART: Record<string, { I: string; II?: string }> = {
    'm-1': { I: art127, II: art128 },
    'm-2': { I: art127, II: art128 },
    'm-3': { I: art127, II: art128 },
    'm-4': { I: art127, II: art129 },
    'm-5': { I: art127, II: art129 },
    'm-6': { I: art127, II: art129 },
    'm-7': { I: art130, II: art131 },
    'm-8': { I: art130, II: art132 },
    'm-9': { I: art133, II: art134 },
    'm-10': { I: art135, II: art136 },
    'm-11': { I: art137, II: art138 },
    'm-12': { I: art139, II: art131 },
    'm-13': { I: art140, II: art141 },
    'm-14': { I: art140, II: art142 },
    'm-15': { I: art143, II: art134 },
    'm-16': { I: art144, II: art136 },
    'm-17': { I: art145, II: art146 },
    'm-18': { I: art145, II: art146 },
    'o-1': { I: art147, II: art148 },
    'o-2': { I: art149, II: art150 },
    'o-3': { I: art151, II: art152 },
    'o-4': { I: art153, II: art154 },
    'o-5': { I: art155, II: art156 },
    'o-6': { I: art157, II: art158 },
    'o-7': { I: art159, II: art148 },
    'o-8': { I: art160, II: art161 },
    'o-9': { I: art162, II: art163 },
    'o-10': { I: art162, II: art163 },
    'o-11': { I: art164, II: art165 },
    'o-12': { I: art166, II: art163 },
    'l-1': { I: art167, II: art168 },
    'l-2': { I: art167, II: art168 },
    'l-3': { I: art169, II: art170 },
    'l-4': { I: art169, II: art171 },
    'l-5': { I: art172, II: art171 },
    'l-6': { I: art172, II: art171 },
    'l-7': { I: art173, II: art174 },
    'l-8': { I: art175, II: art176 },
    'l-9': { I: art177, II: art178 },
    'l-10': { I: art177, II: art178 },
    'l-11': { I: art179, II: art180 },
    'l-12': { I: art179, II: art180 },
    'l-13': { I: art181, II: art182 },
    'l-14': { I: art183, II: art170 },
    'l-15': { I: art184, II: art185 },
    'l-16': { I: art186, II: art187 },
    'h-1': { I: art188, II: art189 },
    'h-2': { I: art188, II: art189 },
    'h-3': { I: art188, II: art189 },
    'h-4': { I: art188, II: art189 },
    'h-5': { I: art188, II: art189 },
    'h-6': { I: art190, II: art191 },
    'h-7': { I: art192, II: art193 },
    'h-8': { I: art194, II: art195 },
    'h-9': { I: art194, II: art195 },
    'h-10': { I: art194, II: art195 },
    'h-11': { I: art196, II: art197 },
    'h-12': { I: art196, II: art197 },
    'h-13': { I: art196, II: art197 },
    'h-14': { I: art198, II: art199 },
    'h-15': { I: art198, II: art199 },
    'h-16': { I: art200, II: art201 },
    'p-1': { I: art202, II: art203 },
    'p-2': { I: art204, II: art205 },
    'p-3': { I: art204, II: art205 },
    'p-4': { I: art206, II: art207 },
    'p-5': { I: art208, II: art209 },
    'p-6': { I: art208, II: art209 },
    'p-7': { I: art210, II: art211 },
    'p-8': { I: art212, II: art213 },
    'p-9': { I: art214, II: art215 },
    'p-10': { I: art214, II: art215 },
    'p-11': { I: art216, II: art217 },
    'p-12': { I: art218, II: art217 },
    'p-13': { I: art218, II: art217 },
    'p-14': { I: art219, II: art220 },
    'k-1': { I: art221, II: art222 },
    'k-2': { I: art221, II: art222 },
    'k-3': { I: art223, II: art224 },
    'k-4': { I: art223, II: art224 },
    'k-5': { I: art225, II: art224 },
    'k-6': { I: art226, II: art224 },
    'k-7': { I: art227, II: art228 },
    'k-8': { I: art229, II: art230 },
    'k-9': { I: art229, II: art230 },
    'k-10': { I: art231, II: art232 },
    'k-11': { I: art233, II: art234 },
    'k-12': { I: art235, II: art236 },
    'k-13': { I: art237, II: art238 },
    'k-14': { I: art237, II: art238 },
    'k-15': { I: art239, II: art240 },
    'k-16': { I: art241, II: art242 },
    'k-17': { I: art241, II: art242 },
    'k-18': { I: art241, II: art242 },
    'k-19': { I: art243, II: art244 },
    'k-20': { I: art243, II: art244 },
    'k-21': { I: art245, II: art244 },
    'k-22': { I: art246, II: art247 },
    'k-23': { I: art248, II: art249 },
    'a-1': { I: art250, II: art251 },
    'a-2': { I: art252, II: art253 },
    'a-3': { I: art254, II: art255 },
    'a-4': { I: art254, II: art255 },
    'a-5': { I: art256, II: art257 },
    'a-6': { I: art256, II: art257 },
    'a-7': { I: art258, II: art259 },
    'a-8': { I: art260, II: art261 },
    'a-9': { I: art260, II: art261 },
    'a-10': { I: art262, II: art263 },
    'a-11': { I: art264, II: art263 },
    'j-1': { I: art265, II: art266 },
    'j-2': { I: art265, II: art267 },
    'j-3': { I: art265, II: art267 },
    'j-4': { I: art265, II: art267 },
    'j-5': { I: art268, II: art269 },
    'j-6': { I: art270, II: art271 },
    'j-7': { I: art272, II: art273 },
    'j-8': { I: art272, II: art273 },
    'j-9': { I: art274, II: art275 },
    'j-10': { I: art276, II: art277 },
    'j-11': { I: art276, II: art277 },
    'j-12': { I: art276, II: art278 },
    'j-13': { I: art279, II: art280 },
    'j-14': { I: art281, II: art282 },
    'j-15': { I: art281, II: art282 },
    'j-16': { I: art283, II: art284 },
    'j-17': { I: art269, II: art285 },
    'j-18': { I: art286, II: art285 },
    'j-19': { I: art286, II: art285 },
    'j-20': { I: art287, II: art288 },
    'd-1': { I: art289, II: art290 },
    'd-2': { I: art291, II: art292 },
    'd-3': { I: art293, II: art294 },
    'd-4': { I: art295, II: art296 },
    'd-5': { I: art295, II: art296 },
    'd-6': { I: art297, II: art298 },
    'd-7': { I: art297, II: art298 },
    'd-8': { I: art299, II: art300 },
    'd-9': { I: art301, II: art302 },
    'd-10': { I: art301, II: art302 },
    'd-11': { I: art303, II: art304 },
    'd-12': { I: art305, II: art306 },
    'e-1': { I: art307, II: art308 },
    'e-2': { I: art307, II: art308 },
    'e-3': { I: art309, II: art310 },
    'e-4': { I: art309, II: art310 },
    'e-5': { I: art311, II: art312 },
    'e-6': { I: art313, II: art314 },
    'e-7': { I: art315, II: art316 },
    'none-1': { I: art317 },
    'none-2': { I: art317 },
    'none-3': { I: art317 },
    'none-4': { I: art317 },
    'none-5': { I: art317 },
    'none-6': { I: art317 },
    'none-7': { I: art317 },
    'none-8': { I: art317 },
    'none-9': { I: art317 },
    'none-10': { I: art317 },
    'none-11': { I: art317 }
}

export const FACTION_ART: Record<string, string> = {
    Consortium: art318,
    Givers: art320,
    Praetorians: art322,
    Starfarers: art324,
    Syndicate: art326,
    Transhumanists: art328,
    TruePath: art330
}

export const SETTLEMENT_ART: Record<string, string> = {
    Consortium: art319,
    Givers: art321,
    Praetorians: art323,
    Starfarers: art325,
    Syndicate: art327,
    Transhumanists: art329,
    TruePath: art331
}

export const TECH_MARKER_ART: Record<string, string> = {
    'Biology-1': art332,
    'Biology-2': art333,
    'Biology-3': art334,
    'Biology-4': art335,
    'Biology-5': art336,
    'Physics-1': art338,
    'Physics-2': art339,
    'Physics-3': art340,
    'Physics-4': art341,
    'Physics-5': art342,
    'Engineering-1': art344,
    'Engineering-2': art345,
    'Engineering-3': art346,
    'Engineering-4': art347,
    'Engineering-5': art348
}

export const EXPLORATION_MARKER_ART: Record<string, string> = {
    Biology: art337,
    Physics: art343,
    Engineering: art349
}

export const TECH_TREE_ART = techTree
