export enum ActionType {
    PlaceBid = 'PlaceBid',
    PassBid = 'PassBid',
    ChooseSide = 'ChooseSide',
    DeployArmy = 'DeployArmy',
    Move = 'Move',
    Attach = 'Attach',
    ThreatenAttack = 'ThreatenAttack',
    DeclareDefense = 'DeclareDefense',
    DeclareFeint = 'DeclareFeint',
    PressAttack = 'PressAttack',
    DeclareAttack = 'DeclareAttack',
    CounterAttack = 'CounterAttack',
    AssignLosses = 'AssignLosses',
    Regroup = 'Regroup',
    Advance = 'Advance',
    Retreat = 'Retreat',
    Occupy = 'Occupy',
    EndTurn = 'EndTurn'
}
