export enum ActionType {
    ChooseMove = 'ChooseMove',
    ChooseConvert = 'ChooseConvert',
    ChooseActivate = 'ChooseActivate',
    Launch = 'Launch',
    Fly = 'Fly',
    Hurl = 'Hurl',
    Convert = 'Convert',
    Activate = 'Activate',
    ActivateBonus = 'ActivateBonus',
    Pass = 'Pass',
    DrawCards = 'DrawCards',
    SolarFlare = 'SolarFlare',
    ChooseCard = 'ChooseCard',
    ActivateEffect = 'ActivateEffect',
    Invade = 'Invade',
    Sacrifice = 'Sacrifice',
    Hatch = 'Hatch',
    Blight = 'Blight',
    Accelerate = 'Accelerate',
    Fuel = 'Fuel',
    Tribute = 'Tribute'
}
