import { expect, test } from '@playwright/test'

test('offered auction history stays in one card through bids, award, reload and Undo', async ({
    page
}) => {
    await page.goto('/table')
    await page.getByLabel('Position', { exact: true }).selectOption('opening')
    await page.getByRole('tab', { name: 'History', exact: true }).click()
    const offers = page.getByRole('region', { name: 'Auction offers' })
    await offers
        .getByRole('button', { name: /^Offer / })
        .first()
        .click()
    const history = page.getByRole('list', { name: 'Action history' })
    const cards = history.getByRole('article')
    await expect(cards).toHaveCount(1)
    await expect(cards.first()).toContainText('offered')
    const auction = page.getByRole('article', { name: 'Current auction' })
    const amount = await auction.locator('output').innerText()
    await auction.getByRole('button', { name: 'Bid', exact: true }).click()
    await expect(cards.first()).toContainText(`bid ${amount}`)
    await auction.getByRole('button', { name: 'Pass', exact: true }).click()
    await expect(cards).toHaveCount(1)
    await expect(cards.first()).toContainText('passed')
    await expect(cards.first()).toContainText('won')
    const completed = await cards.first().innerText()
    await page.reload()
    await page.getByLabel('Position', { exact: true }).selectOption('opening')
    await page.getByRole('tab', { name: 'History', exact: true }).click()
    await expect(cards.first()).toHaveText(completed, { useInnerText: true })
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(cards.first()).not.toContainText('won')
    await expect(cards.first()).not.toContainText('passed')
    await expect(cards.first()).toContainText('bid')
})
