export const COMPANY_DEED_VIEWBOX_WIDTH = 832.24
export const COMPANY_DEED_VIEWBOX_HEIGHT = 551.63
export const COMPANY_DEED_VIEWBOX_RX = 67.48
export const COMPANY_DEED_VIEWBOX_RY = 67.48
export const COMPANY_DEED_ASPECT_RATIO = COMPANY_DEED_VIEWBOX_WIDTH / COMPANY_DEED_VIEWBOX_HEIGHT

export const BOARD_DEED_CARD_HEIGHT = 58
export const BOARD_DEED_CARD_WIDTH = BOARD_DEED_CARD_HEIGHT * COMPANY_DEED_ASPECT_RATIO
export const BOARD_DEED_CARD_CORNER_RX =
    (BOARD_DEED_CARD_WIDTH / COMPANY_DEED_VIEWBOX_WIDTH) * COMPANY_DEED_VIEWBOX_RX
export const BOARD_DEED_CARD_CORNER_RY =
    (BOARD_DEED_CARD_HEIGHT / COMPANY_DEED_VIEWBOX_HEIGHT) * COMPANY_DEED_VIEWBOX_RY
