import { expect, test, type Page } from '@playwright/test'
async function openSplit(page: Page) {
    await page.goto('/economy')
    await page.getByLabel('Example position').selectOption('split')
    return page.getByRole('region', { name: 'Branch split preview', exact: true })
}
async function selectSplit(page: Page) {
    const panel = await openSplit(page)
    await panel.locator('[data-split-parent="So"]').click()
    await panel.locator('[data-split-branch="branch:BB"]').click()
    await panel.locator('[data-split-price="3:1"]').click()
    return panel
}
test('previews the split, changes prices, and unwinds manual selections with Undo', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    const panel = await selectSplit(page)
    await expect(panel.getByRole('table', { name: 'Split share ownership' })).toBeVisible()
    await expect(panel.getByRole('article', { name: 'Branch funding' })).toContainText('$560')
    await expect(panel).toContainText('3 more shares must leave the Bank before flotation')
    await expect(panel).toContainText('Protected parent home')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await panel.locator('[data-split-price="5:1"]').click()
    await expect(panel.getByRole('article', { name: 'Branch funding' })).toContainText('$455')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await panel.locator('[data-split-branch="branch:CB"]').click()
    await expect(panel.locator('[data-split-price]').first()).toBeVisible()
    await expect(panel.getByRole('table')).toHaveCount(0)
    await panel.locator('[data-split-price="3:1"]').click()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.locator('[data-split-price]').first()).toBeVisible()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.locator('[data-split-branch]').first()).toBeVisible()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.locator('[data-split-parent]').first()).toBeVisible()
    await expect(panel.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
    await panel.locator('[data-split-parent="So"]').click()
    await panel.locator('[data-split-branch="branch:BB"]').click()
    await panel.locator('[data-split-price="3:1"]').click()
    await panel.screenshot({ path: '/tmp/17a-split-preview.png' })
    expect(errors).toEqual([])
})
test('does not persist the preview and clears it when a stock action changes canonical state', async ({
    page
}) => {
    let panel = await selectSplit(page)
    await page.reload()
    panel = await openSplit(page)
    await expect(panel.locator('[data-split-parent]').first()).toBeVisible()
    await expect(panel.getByRole('table')).toHaveCount(0)
    panel = await selectSplit(page)
    const stock = page.getByRole('region', { name: 'Stock trading', exact: true })
    await stock.getByRole('button', { name: 'Pass', exact: true }).click()
    await expect(panel.locator('[data-split-parent]').first()).toBeVisible()
    await expect(panel.getByRole('table')).toHaveCount(0)
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.locator('[data-split-parent]').first()).toBeVisible()
    await panel.locator('[data-split-parent="So"]').click()
    await panel.locator('[data-split-branch="branch:BB"]').click()
    await panel.locator('[data-split-price="3:1"]').click()
    await expect(panel.getByRole('article', { name: 'Branch funding' })).toContainText('$560')
    await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
    await expect(
        page.getByRole('region', { name: 'Branch split preview', exact: true })
    ).toHaveCount(0)
    await expect(page.getByLabel('Example position')).toHaveValue('trading')
})

test('allocates assets, confirms the split, reloads it, and undoes the whole transaction', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    let panel = await selectSplit(page)
    await panel.getByRole('button', { name: 'Allocate assets', exact: true }).click()
    await expect(panel.getByRole('button', { name: 'Confirm split', exact: true })).toBeDisabled()
    const stations = panel.getByRole('group', { name: 'Stations for the branch', exact: true })
    await expect(
        stations.getByRole('checkbox', { name: 'Souris (protected home)', exact: true })
    ).toBeDisabled()
    await stations.getByRole('checkbox', { name: 'Cornwall', exact: true }).check()
    await stations.getByRole('checkbox', { name: 'Belfast', exact: true }).check()
    await expect(panel.getByRole('button', { name: 'Confirm split', exact: true })).toBeDisabled()
    await panel.getByRole('radio', { name: 'Cornwall', exact: true }).check()
    await panel
        .getByRole('group', { name: 'Trains for the branch', exact: true })
        .getByRole('checkbox')
        .check()
    await panel.getByLabel('Cash to branch', { exact: true }).fill('110')
    await panel.getByRole('checkbox', { name: 'Transfer Hunslet to branch', exact: true }).check()
    await expect(panel).toContainText('Branch: $670')
    await panel.screenshot({ path: '/tmp/17b-allocation.png' })
    await panel.getByRole('button', { name: 'Confirm split', exact: true }).click()
    await expect(panel.getByRole('status')).toContainText('Souris split into Belfast Branch')
    await expect(panel.getByRole('status')).toContainText('$560')
    await expect(panel.getByRole('button', { name: 'Confirm split', exact: true })).toHaveCount(0)
    const map = page.getByRole('region', { name: 'Game map', exact: true })
    await expect(map.locator('[data-map-token="branch:BB:home"]')).toContainText('BB')
    await expect(map.locator('[data-map-token="branch:BB:station:1"]')).toContainText('BB')
    await expect(map.locator('[data-map-token="So:station:1"]')).toHaveCount(0)
    await expect(map.locator('[data-map-token="So:station:2"]')).toHaveCount(0)
    await map.screenshot({ path: '/tmp/17b-map.png' })
    await expect(
        page
            .getByRole('region', { name: 'Stock trading', exact: true })
            .getByRole('button', { name: 'End turn', exact: true })
    ).toBeVisible()
    await page.screenshot({ path: '/tmp/17b-committed.png', fullPage: true })
    await page.reload()
    panel = await openSplit(page)
    await expect(panel.getByRole('status')).toContainText('Souris split into Belfast Branch')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.getByRole('status')).toHaveCount(0)
    await expect(map.locator('[data-map-token="branch:BB:home"]')).toHaveCount(0)
    await expect(map.locator('[data-map-token="So:station:1"]')).toContainText('So')
    await expect(map.locator('[data-map-token="So:station:2"]')).toContainText('So')
    await panel.locator('[data-split-parent="So"]').click()
    await panel.locator('[data-split-branch="branch:BB"]').click()
    await panel.locator('[data-split-price="3:1"]').click()
    await expect(panel).toContainText('Parent cash: $120')
    await expect(panel.getByRole('article', { name: 'Branch funding' })).toContainText('$560')
    await expect(panel).toContainText('Hunslet Steam Engine: Available')
    expect(errors).toEqual([])
})

test('Back discards allocation choices while preserving the financial preview', async ({
    page
}) => {
    const panel = await selectSplit(page)
    await panel.getByRole('button', { name: 'Allocate assets', exact: true }).click()
    await panel.getByLabel('Cash to branch', { exact: true }).fill('121')
    await expect(panel.getByRole('button', { name: 'Confirm split', exact: true })).toBeDisabled()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.getByRole('table', { name: 'Split share ownership' })).toBeVisible()
    await expect(panel.getByRole('button', { name: 'Confirm split', exact: true })).toHaveCount(0)
    await panel.getByRole('button', { name: 'Allocate assets', exact: true }).click()
    await expect(panel.getByLabel('Cash to branch', { exact: true })).toHaveValue('0')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.getByRole('table', { name: 'Split share ownership' })).toBeVisible()
    await expect(panel.getByRole('button', { name: 'Allocate assets', exact: true })).toBeVisible()
})
