import { expect, test, type Page } from '@playwright/test'
async function position(page: Page, title: string, example: string) {
    if (title === '1889')
        await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
    await page.getByLabel('Example position').selectOption(example)
}
for (const title of ['TOP', '1889']) {
    test(`${title} negotiates a purchase with Back, response, reload and Undo`, async ({
        page
    }) => {
        const errors: string[] = []
        page.on('pageerror', (error) => errors.push(error.message))
        await page.goto('/economy')
        await position(page, title, 'transfers')
        const panel = page.getByRole('region', { name: 'Company decisions', exact: true })
        const asset = panel.getByLabel('Purchase asset')
        await asset.selectOption('0')
        const preview = panel.getByLabel('Company decision preview')
        await expect(preview).toBeVisible()
        await panel.getByRole('button', { name: 'Back', exact: true }).click()
        await expect(preview).toHaveCount(0)
        await asset.selectOption('0')
        await panel.getByLabel('Offer price').fill('17')
        await panel.getByRole('button', { name: 'Confirm decision', exact: true }).click()
        const response = panel.getByLabel('Purchase response')
        await expect(response).toContainText('offers 17')
        await page.reload()
        await position(page, title, 'transfers')
        await expect(response).toContainText('offers 17')
        await panel.getByRole('button', { name: 'Reject purchase', exact: true }).click()
        await expect(response).toHaveCount(0)
        await asset.selectOption('0')
        await panel.getByLabel('Offer price').fill('17')
        await panel.getByRole('button', { name: 'Confirm decision', exact: true }).click()
        await panel.getByRole('button', { name: 'Accept purchase', exact: true }).click()
        await expect(response).toHaveCount(0)
        await panel.getByRole('button', { name: 'Undo', exact: true }).click()
        await expect(response).toContainText('offers 17')
        await panel.getByRole('button', { name: 'Undo', exact: true }).click()
        await expect(response).toHaveCount(0)
        expect(errors).toEqual([])
    })
}
test('1889 gives Ehime’s seller an extra tile without spending the ordinary lay', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await position(page, '1889', 'powers')
    const panel = page.getByRole('region', { name: 'Company decisions', exact: true })
    const value = await panel
        .getByLabel('Purchase asset')
        .locator('option')
        .filter({ hasText: 'ER ·' })
        .getAttribute('value')
    await panel.getByLabel('Purchase asset').selectOption(value!)
    await panel.getByRole('button', { name: 'Confirm decision', exact: true }).click()
    await panel.getByRole('button', { name: 'Accept purchase', exact: true }).click()
    await expect(panel).toContainText('Alex may use ER')
    await page.reload()
    await position(page, '1889', 'powers')
    await expect(panel).toContainText('Alex may use ER')
    await panel.getByLabel('Private tile lay', { exact: true }).selectOption('0')
    await expect(panel.getByLabel('Company decision preview')).toContainText('Alex uses ER')
    await panel.getByRole('button', { name: 'Confirm decision', exact: true }).click()
    await expect(panel.getByRole('button', { name: 'Decline private tile lay' })).toHaveCount(0)
    const track = page.getByRole('region', { name: 'Track construction', exact: true })
    await expect(track).toContainText('0 placed')
    await expect(track.getByRole('button', { name: 'Finish track', exact: true })).toBeEnabled()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel).toContainText('Alex may use ER')
    expect(errors).toEqual([])
})
test('TOP acquires and uses Hunslet before laying track', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await position(page, 'TOP', 'powers')
    const panel = page.getByRole('region', { name: 'Company decisions', exact: true })
    await panel.getByLabel('Purchase asset').selectOption('0')
    await panel.getByRole('button', { name: 'Confirm decision', exact: true }).click()
    await panel.getByRole('button', { name: 'Accept purchase', exact: true }).click()
    await panel.getByLabel('Private train purchase').selectOption('0')
    await expect(panel.getByLabel('Company decision preview')).toContainText('closes HS')
    await panel.getByRole('button', { name: 'Confirm decision', exact: true }).click()
    await expect(
        page.getByRole('article', { name: 'Hunslet Steam Engine', exact: true })
    ).toContainText('Closed')
    await expect(
        page.getByRole('region', { name: 'Track construction', exact: true })
    ).toContainText('0 placed')
    await expect(panel.getByLabel('Private train purchase')).toHaveCount(0)
    expect(errors).toEqual([])
})
test('Mitsubishi’s owner selects a port without owning a railway', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await position(page, '1889', 'privates')
    const panel = page.getByRole('region', { name: 'Company decisions', exact: true })
    await panel.getByLabel('Private tile lay', { exact: true }).selectOption('0')
    const preview = panel.getByLabel('Company decision preview')
    await expect(preview).toContainText('Casey uses MF')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(preview).toHaveCount(0)
    await panel.getByLabel('Private tile lay', { exact: true }).selectOption('0')
    await panel.getByRole('button', { name: 'Confirm decision', exact: true }).click()
    await expect(panel.getByLabel('Private tile lay', { exact: true })).toHaveCount(0)
    await expect(
        page.getByRole('article', { name: 'Mitsubishi Ferry', exact: true })
    ).not.toContainText('Closed')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.getByLabel('Private tile lay', { exact: true })).toBeVisible()
    expect(errors).toEqual([])
})
test('TOP requests permission for Vernon River Bridge and records the accepted lay', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await position(page, 'TOP', 'powers')
    const track = page.getByRole('region', { name: 'Track construction', exact: true })
    await track.getByLabel('Construction hex').selectOption('N18')
    await track.getByRole('button', { name: 'Build tile 7', exact: true }).click()
    await track.locator('[data-track-rotation]').first().click()
    await track.getByRole('button', { name: 'Request track permission', exact: true }).click()
    const panel = page.getByRole('region', { name: 'Company decisions', exact: true })
    await expect(panel.getByLabel('Track permission response')).toContainText('Casey decides')
    await page.reload()
    await position(page, 'TOP', 'powers')
    await panel.getByRole('button', { name: 'Allow track lay', exact: true }).click()
    await expect(track.getByLabel('Construction history')).toContainText('N18')
    await expect(track).toContainText('1 placed')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.getByLabel('Track permission response')).toBeVisible()
    expect(errors).toEqual([])
})
test('Mitsubishi can skip a between-company window without spending the power', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await position(page, '1889', 'transfers')
    await page.getByRole('button', { name: 'Finish operating turn', exact: true }).click()
    const panel = page.getByRole('region', { name: 'Company decisions', exact: true })
    await expect(panel).toContainText('Private powers before AR operates')
    await page.reload()
    await position(page, '1889', 'transfers')
    await expect(panel.getByLabel('Private tile lay', { exact: true })).toBeVisible()
    await panel.getByRole('button', { name: 'Continue operating round', exact: true }).click()
    await expect(
        page.getByRole('region', { name: 'Track construction', exact: true })
    ).toBeVisible()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.getByLabel('Private tile lay', { exact: true })).toBeVisible()
    expect(errors).toEqual([])
})
