import { expect, test } from '@playwright/test'
test('TOP stages track, pays for its second lay, and undoes through history and reload', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await page.getByLabel('Example position').selectOption('construction')
    const panel = page.getByRole('region', { name: 'Track construction', exact: true })
    const map = page.getByRole('region', { name: 'Game map', exact: true })
    await page.getByLabel('Construction hex').selectOption('K17')
    await panel.locator('[data-track-tile="18xx:8"]').click()
    await panel.locator('[data-track-rotation="2"]').click()
    await expect(page.locator('[data-track-preview="K17"]')).toHaveCount(1)
    await expect(map.getByRole('status')).toHaveText('Live · 0 actions')
    await map.getByLabel('Tile style').selectOption('muted')
    await panel.getByRole('button', { name: 'Back', exact: true }).click()
    await expect(page.locator('[data-track-preview]')).toHaveCount(0)
    await expect(panel.getByRole('button', { name: 'Confirm track', exact: true })).toHaveCount(0)
    await panel.locator('[data-track-rotation="2"]').click()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(page.getByLabel('Construction hex')).toBeVisible()
    await expect(map.getByRole('status')).toHaveText('Live · 0 actions')
    await page.getByLabel('Construction hex').selectOption('K17')
    await panel.locator('[data-track-tile="18xx:8"]').click()
    await panel.locator('[data-track-rotation="2"]').click()
    await panel.getByRole('button', { name: 'Confirm track', exact: true }).click()
    await expect(map.getByRole('status')).toHaveText('Live · 1 actions')
    await expect(panel).toContainText('1 placed')
    const second = await page
        .getByLabel('Construction hex')
        .locator('option')
        .nth(1)
        .getAttribute('value')
    if (!second) throw new Error('Missing second lay')
    await page.getByLabel('Construction hex').selectOption(second)
    await panel.locator('[data-track-tile]').first().click()
    await panel.locator('[data-track-rotation]').first().click()
    await expect(panel).toContainText('lay $20')
    await panel.getByRole('button', { name: 'Confirm track', exact: true }).click()
    await expect(panel).toContainText('2 placed')
    await expect(panel).toContainText('No legal construction')
    await map.getByRole('button', { name: 'Beginning', exact: true }).click()
    await expect(page.locator('[data-map-location="K17"]')).toHaveAttribute('data-placed', 'false')
    await expect(page.locator('[data-track-preview]')).toHaveCount(0)
    await map.getByRole('button', { name: 'Live', exact: true }).click()
    await page.reload()
    await page.getByLabel('Example position').selectOption('construction')
    await expect(panel).toContainText('2 placed')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel).toContainText('1 placed')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel).toContainText('0 placed')
    await expect(panel).toContainText('Treasury: $920')
    expect(errors).toEqual([])
})
test('1889 previews an upgrade, preserves its station, returns the yellow tile, and finishes track', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
    await page.getByLabel('Example position').selectOption('construction')
    const panel = page.getByRole('region', { name: 'Track construction', exact: true })
    const map = page.getByRole('region', { name: 'Game map', exact: true })
    await page.getByLabel('Construction hex').selectOption('E2')
    await panel.locator('[data-track-tile="18xx:12"]').click()
    await expect(page.locator('[data-track-preview="E2"]')).toHaveCount(1)
    await expect(page.locator('[data-map-token="IR:home"]')).toHaveCount(1)
    await panel.getByRole('button', { name: 'Back', exact: true }).click()
    await expect(panel.locator('[data-track-tile]')).not.toHaveCount(0)
    await panel.locator('[data-track-tile="18xx:12"]').click()
    await panel.getByRole('button', { name: 'Confirm track', exact: true }).click()
    await expect(panel).toContainText('No legal construction')
    await expect(map.getByRole('complementary', { name: 'Map inspection' })).toContainText('green')
    await panel.getByRole('button', { name: 'Finish track', exact: true }).click()
    await expect(panel).toContainText('Track complete')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel).toContainText('1 placed')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel).toContainText('0 placed')
    await expect(map.getByRole('complementary', { name: 'Map inspection' })).toContainText('yellow')
    expect(errors).toEqual([])
})
