import { expect, test } from '@playwright/test'

test('Map owns F when both views are visible, including after Map is reopened', async ({ page }) => {
    await page.goto('/table')
    await page.getByRole('tab', { name: 'Market', exact: true }).dragTo(page.getByRole('tab', { name: 'Game info', exact: true }))
    const map = page.getByRole('tabpanel', { name: 'Map', exact: true })
    const market = page.getByRole('tabpanel', { name: 'Market', exact: true })
    await page.keyboard.press('f')
    await expect(map.getByRole('button', { name: 'Exit full screen' })).toBeVisible()
    await expect(market.getByRole('button', { name: 'Exit full screen' })).toHaveCount(0)
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Pane options for Table views pane 4' }).click()
    await page.getByRole('button', { name: 'Close Map tab', exact: true }).click()
    await page.keyboard.press('Escape')
    await page.keyboard.press('f')
    await expect(market.getByRole('button', { name: 'Exit full screen' })).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Pane options for Table views pane 4' }).click()
    await page.getByRole('button', { name: 'Map', exact: true }).click()
    await page.keyboard.press('f')
    await expect(map.getByRole('button', { name: 'Exit full screen' })).toBeVisible()
    await expect(market.getByRole('button', { name: 'Exit full screen' })).toHaveCount(0)
    await page.keyboard.press('Escape')
    await page.getByRole('tab', { name: 'Tiles', exact: true }).click()
    await page.keyboard.press('f')
    await expect(market.getByRole('button', { name: 'Exit full screen' })).toBeVisible()
    await page.keyboard.press('Escape')
    await page.getByRole('tab', { name: 'Map', exact: true }).click()
    await market.getByRole('button', { name: 'Enter full screen' }).click()
    await expect(market.getByRole('button', { name: 'Exit full screen' })).toBeVisible()
})

test('fullscreen renders above other panes and dividers without remounting its content', async ({ page }) => {
    await page.goto('/table')
    await page.getByRole('tab', { name: 'Market', exact: true }).dragTo(page.getByRole('tab', { name: 'Game info', exact: true }))
    const map = page.getByRole('tabpanel', { name: 'Map', exact: true })
    const market = page.getByRole('tabpanel', { name: 'Market', exact: true })
    const marketBounds = await market.boundingBox()
    const dividerBounds = await page.getByRole('separator', { name: 'Resize vertical split' }).boundingBox()
    if (!marketBounds || !dividerBounds) throw new Error('Both panes and divider must be visible')
    await map.locator('.scaling-surface').evaluate(element => element.dataset.mountCheck = 'preserved')
    await page.keyboard.press('f')
    await expect(map.getByRole('button', { name: 'Exit full screen' })).toBeVisible()
    const points = [marketBounds, dividerBounds].map(rect => ({ x: rect.x + rect.width / 2, y: rect.y + rect.height / 2 }))
    expect(await map.locator('.scaling-surface').evaluate((element, points) => points.every(point => element.parentElement?.contains(document.elementFromPoint(point.x, point.y))), points)).toBe(true)
    await page.keyboard.press('Escape')
    await expect(map.locator('.scaling-surface')).toHaveAttribute('data-mount-check', 'preserved')
    await expect(market.getByRole('button', { name: 'Enter full screen' })).toBeVisible()
})
