import { expect, test } from '@playwright/test'

test('TOP map follows flotation, history, Live and Undo without losing inspection', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await page.getByLabel('Example position').selectOption('flotation')
    const map = page.getByRole('region', { name: 'Game map', exact: true })
    const stock = page.getByRole('region', { name: 'Stock trading', exact: true })
    const inspector = page.getByRole('complementary', { name: 'Map inspection' })
    await expect(page.locator('[data-map-location]')).toHaveCount(110)
    await expect(page.locator('[data-map-token="PEIR:A"]')).toBeVisible()
    await page.getByRole('button', { name: 'D6 city slot 1', exact: true }).press('Enter')
    await expect(inspector).toContainText('Station: PEIR')
    await expect(inspector).toContainText('Home reservation: A')
    await map.getByLabel('Tile style').selectOption('muted')
    await map.getByRole('button', { name: 'Focus selection', exact: true }).click()
    await page.locator('[data-purchase-certificate="A:share:4"][data-buyer="player"]').click()
    await stock.getByRole('button', { name: 'Confirm purchase', exact: true }).click()
    await expect(page.locator('[data-map-token="A:home"]')).toBeVisible()
    await expect(page.locator('[data-map-token="PEIR:A"]')).toHaveCount(0)
    await expect(inspector).toContainText('Station: A')
    await expect(inspector).not.toContainText('Home reservation: A')
    await expect(page.locator('[data-map-highlight="D6"]')).toHaveCount(1)
    await map.getByRole('button', { name: 'Beginning', exact: true }).click()
    await expect(page.locator('[data-map-token="PEIR:A"]')).toBeVisible()
    await expect(inspector).toContainText('Home reservation: A')
    await expect(stock.getByRole('button', { name: 'Pass', exact: true })).toBeDisabled()
    await map.getByRole('button', { name: 'Next action', exact: true }).click()
    await expect(map.getByRole('status')).toHaveText('History · 1 actions')
    await expect(page.locator('[data-map-token="PEIR:A"]')).toBeVisible()
    await map.getByRole('button', { name: 'Next action', exact: true }).click()
    await expect(page.locator('[data-map-token="A:home"]')).toBeVisible()
    await map.getByRole('button', { name: 'Previous action', exact: true }).click()
    await map.getByRole('button', { name: 'Live', exact: true }).click()
    await expect(map.getByRole('status')).toHaveText('Live · 2 actions')
    await stock.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(page.locator('[data-map-token="PEIR:A"]')).toBeVisible()
    await expect(inspector).toContainText('Home reservation: A')
    await expect(map.getByRole('status')).toHaveText('Live · 0 actions')
    await expect(map.getByLabel('Tile style')).toHaveValue('muted')
    await expect(page.locator('[data-map-highlight="D6"]')).toHaveCount(1)
    expect(errors).toEqual([])
})

test('1889 map shares inventory and retains its reserved home after flotation and reload', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/economy')
    await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
    await page.getByLabel('Example position').selectOption('flotation')
    const map = page.getByRole('region', { name: 'Game map', exact: true })
    const stock = page.getByRole('region', { name: 'Stock trading', exact: true })
    const inspector = page.getByRole('complementary', { name: 'Map inspection' })
    await expect(page.locator('[data-map-location]')).toHaveCount(52)
    await expect(page.locator('[data-map-location="I2"]')).toHaveAttribute('data-placed', 'true')
    await page.getByRole('button', { name: 'I2 city slot 1', exact: true }).press('Enter')
    await expect(inspector).toContainText('Placed tile · yellow · 120°')
    await expect(inspector).toContainText('Home reservation: SR')
    await map.getByText('Available tiles', { exact: true }).click()
    const tile = map.getByRole('button', { name: 'Inspect 5, Shared 18xx', exact: true })
    await expect(tile.locator('[data-tile-inventory]')).toHaveText('1 / 2 available')
    await tile.click()
    await expect(map.getByRole('complementary', { name: 'Tile inspection' })).toContainText(
        '1 of 2 available'
    )
    await page.locator('[data-purchase-certificate="SR:share:3"]').click()
    await stock.getByRole('button', { name: 'Confirm purchase', exact: true }).click()
    await expect(inspector).toContainText('Home reservation: SR')
    await expect(page.locator('[data-map-token="SR:home"]')).toHaveCount(0)
    await page.reload()
    await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
    await page.getByLabel('Example position').selectOption('flotation')
    await expect(page.locator('[data-map-location="I2"]')).toHaveAttribute('data-placed', 'true')
    await page.getByRole('button', { name: 'I2 city slot 1', exact: true }).press('Enter')
    await expect(inspector).toContainText('Home reservation: SR')
    await expect(page.locator('[data-company-lifecycle="SR"]')).toContainText('Funded · Floated')
    expect(errors).toEqual([])
})

test('hotseat map styles belong to each player and do not create actions', async ({ page }) => {
    await page.goto('/economy')
    const map = page.getByRole('region', { name: 'Game map', exact: true })
    const stock = page.getByRole('region', { name: 'Stock trading', exact: true })
    await page.getByRole('button', { name: 'K19 Cornwall', exact: true }).press('Enter')
    await map.getByLabel('Tile style').selectOption('muted')
    await expect(map.getByRole('status')).toHaveText('Live · 0 actions')
    await stock.getByRole('button', { name: 'Pass', exact: true }).click()
    await expect(map.getByLabel('Tile style')).toHaveValue('classic')
    await expect(page.locator('[data-map-highlight="K19"]')).toHaveCount(1)
    await stock.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(map.getByLabel('Tile style')).toHaveValue('muted')
    await expect(map.getByRole('status')).toHaveText('Live · 0 actions')
})
