import { expect, test, type Page } from '@playwright/test'
async function opening(page: Page) {
    await page.goto('/economy')
    await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
    await page.getByLabel('Example position').selectOption('opening')
    return page.getByRole('region', { name: 'Opening auction', exact: true })
}
test('reserves bids, stages Back and Undo, persists a restricted auction and resumes stock trading', async ({
    page
}) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    let panel = await opening(page)
    const ferry = panel.getByRole('article', { name: 'Mitsubishi Ferry', exact: true })
    await ferry.getByRole('button', { name: /Reserve bid/ }).click()
    await panel.getByLabel('Bid amount').fill('36')
    await panel.getByRole('button', { name: 'Back', exact: true }).click()
    await expect(panel.getByLabel('Bid amount')).toHaveCount(0)
    await ferry.getByRole('button', { name: /Reserve bid/ }).click()
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel.getByLabel('Bid amount')).toHaveCount(0)
    await ferry.getByRole('button', { name: /Reserve bid/ }).click()
    await panel.getByLabel('Bid amount').fill('36')
    await panel.getByRole('button', { name: 'Confirm bid', exact: true }).click()
    await expect(ferry).toContainText(': 36')
    await ferry.getByRole('button', { name: /Reserve bid/ }).click()
    await panel.getByRole('button', { name: 'Confirm bid', exact: true }).click()
    await panel.getByRole('button', { name: 'Buy for 20', exact: true }).click()
    await panel.getByRole('button', { name: 'Confirm purchase', exact: true }).click()
    await expect(panel).toContainText('Bidding for Mitsubishi Ferry')
    panel = await openingAfterReload(page)
    await expect(panel).toContainText('Bidding for Mitsubishi Ferry')
    await panel.getByRole('button', { name: /Raise bid/ }).click()
    await panel.getByRole('button', { name: 'Confirm bid', exact: true }).click()
    await panel.getByRole('button', { name: 'Pass auction', exact: true }).click()
    await expect(panel).not.toContainText('Bidding for Mitsubishi Ferry')
    await panel.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel).toContainText('Bidding for Mitsubishi Ferry')
    await panel.getByRole('button', { name: 'Pass auction', exact: true }).click()
    for (let i = 0; i < 4; i++) {
        await panel.getByRole('button', { name: /^Buy for / }).click()
        await panel.getByRole('button', { name: 'Confirm purchase', exact: true }).click()
    }
    await expect(panel).toHaveCount(0)
    const stock = page.getByRole('region', { name: 'Stock trading', exact: true })
    await expect(stock).toBeVisible()
    await expect(page.locator('[data-start-company="AR"]')).toBeVisible()
    await stock.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(panel).toBeVisible()
    await expect(panel.getByRole('button', { name: 'Buy for 80', exact: true })).toBeVisible()
    expect(errors).toEqual([])
})
async function openingAfterReload(page: Page) {
    await page.reload()
    await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
    await page.getByLabel('Example position').selectOption('opening')
    return page.getByRole('region', { name: 'Opening auction', exact: true })
}
test('shows the two- and six-player sets and applies all-pass discounts', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    const panel = await opening(page)
    await page.getByRole('combobox', { name: 'Players', exact: true }).selectOption('6')
    await expect(panel.getByRole('article')).toHaveCount(7)
    await expect(panel).toContainText('Available cash: 390')
    await page.getByRole('combobox', { name: 'Players', exact: true }).selectOption('2')
    await expect(panel.getByRole('article')).toHaveCount(5)
    await expect(panel).toContainText('Available cash: 420')
    for (let i = 0; i < 8; i++)
        await panel.getByRole('button', { name: 'Pass auction', exact: true }).click()
    await expect(panel.getByRole('article')).toHaveCount(4)
    await expect(panel).toContainText('Awarded')
    await expect(panel.getByRole('button', { name: 'Buy for 30', exact: true })).toBeVisible()
    await page.screenshot({ path: '/tmp/s16-auction.png', fullPage: true })
    expect(errors).toEqual([])
})
