import { expect, test } from '@playwright/test'
for (const title of ['TOP', '1889']) {
    test(`${title} previews and places a station, with Back, Undo, history and reload`, async ({
        page
    }) => {
        const errors: string[] = []
        page.on('pageerror', (error) => errors.push(error.message))
        await page.goto('/economy')
        if (title === '1889')
            await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
        await page.getByLabel('Example position').selectOption('stations')
        const panel = page.getByRole('region', { name: 'Station placement', exact: true })
        const map = page.getByRole('region', { name: 'Game map', exact: true })
        const stationId = title === 'TOP' ? 'ML:station:1' : 'IR:station:1'
        const locationId = title === 'TOP' ? 'K19' : 'F3'
        const target = JSON.stringify({ locationId, nodeId: 'city', slot: 0 })
        if (title === '1889') await page.getByLabel('Network company').selectOption('AR')
        await panel.locator(`[data-station-id="${stationId}"]`).click()
        await page.getByLabel('Station position', { exact: true }).selectOption(target)
        await expect(page.locator(`[data-map-token="${stationId}"]`)).toHaveCount(1)
        if (title === '1889')
            await expect(page.getByLabel('Network access')).toContainText('Blocked cities: F3')
        await expect(map.getByRole('status')).toHaveText('Live · 0 actions')
        await expect(panel).toContainText(`Cost: $${title === 'TOP' ? 80 : 40}`)
        await panel.getByRole('button', { name: 'Back', exact: true }).click()
        await expect(page.locator(`[data-map-token="${stationId}"]`)).toHaveCount(0)
        if (title === '1889')
            await expect(page.getByLabel('Network access')).toContainText('Blocked cities: E2')
        await page.getByLabel('Station position', { exact: true }).selectOption(target)
        await panel.getByRole('button', { name: 'Undo', exact: true }).click()
        await expect(panel.locator(`[data-station-id="${stationId}"]`)).toBeVisible()
        await expect(map.getByRole('status')).toHaveText('Live · 0 actions')
        await panel.locator(`[data-station-id="${stationId}"]`).click()
        await page.getByLabel('Station position', { exact: true }).selectOption(target)
        await panel.getByRole('button', { name: 'Confirm station', exact: true }).click()
        await expect(panel).toContainText('1 placed this turn')
        await expect(panel).toContainText(`Treasury: $${title === 'TOP' ? 840 : 560}`)
        await expect(panel).toContainText('No legal station placement')
        await map.getByRole('button', { name: 'Beginning', exact: true }).click()
        await expect(page.locator(`[data-map-token="${stationId}"]`)).toHaveCount(0)
        await expect(
            panel.getByRole('button', { name: 'Finish stations', exact: true })
        ).toBeDisabled()
        await map.getByRole('button', { name: 'Live', exact: true }).click()
        await page.reload()
        if (title === '1889')
            await page.getByRole('button', { name: 'Shikoku 1889', exact: true }).click()
        await page.getByLabel('Example position').selectOption('stations')
        await expect(page.locator(`[data-map-token="${stationId}"]`)).toHaveCount(1)
        await panel.getByRole('button', { name: 'Finish stations', exact: true }).click()
        await expect(panel).toContainText('Station placement complete')
        await panel.getByRole('button', { name: 'Undo', exact: true }).click()
        await expect(panel).toContainText('1 placed this turn')
        await panel.getByRole('button', { name: 'Undo', exact: true }).click()
        await expect(panel).toContainText('0 placed this turn')
        await expect(page.locator(`[data-map-token="${stationId}"]`)).toHaveCount(0)
        expect(errors).toEqual([])
    })
}
