import { expect, test } from '@playwright/test'

test('mouse wheel zooms and dragging pans without clicking the board', async ({ page }) => {
    await page.goto('/session-test.html')
    await page.evaluate(async () => {
        const { mountWrapper } = await import(new URL('/src/lib/components/tests/scalingWrapper.fixture.ts', location.href).href)
        mountWrapper()
    })
    const board = page.getByTestId('board')
    await expect.poll(async () => (await board.boundingBox())?.width).toBe(375)
    await page.mouse.move(200, 150)
    await page.mouse.wheel(0, -200)
    await expect.poll(async () => (await board.boundingBox())?.width).toBeGreaterThan(600)
    const before = await board.boundingBox()
    if (!before) throw new Error('Missing board')
    await page.mouse.down()
    await page.mouse.move(250, 190, { steps: 5 })
    await page.mouse.up()
    const after = await board.boundingBox()
    if (!after) throw new Error('Missing board')
    expect(after.x).toBeCloseTo(before.x + 50)
    expect(after.y).toBeCloseTo(before.y + 40)
    await expect(page.locator('output')).toHaveText('0')
    expect(await page.evaluate(() => window.getSelection()?.toString())).toBe('')
    await expect(board).toHaveCSS('user-select', 'none')
    await page.mouse.click(250, 190)
    await expect(page.locator('output')).toHaveText('1')
    await page.mouse.wheel(0, 2000)
    await expect.poll(async () => (await board.boundingBox())?.width).toBe(375)
})

test('smooth trackpad gestures pan, including their faster continuation, and pinch zooms', async ({ page }) => {
    await page.goto('/session-test.html')
    await page.evaluate(async () => {
        const { mountWrapper } = await import(new URL('/src/lib/components/tests/scalingWrapper.fixture.ts', location.href).href)
        mountWrapper()
    })
    const board = page.getByTestId('board')
    await expect.poll(async () => (await board.boundingBox())?.width).toBe(375)
    await page.mouse.move(200, 150)
    await page.mouse.wheel(0, -200)
    await expect.poll(async () => (await board.boundingBox())?.width).toBeGreaterThan(600)
    const before = await board.boundingBox()
    if (!before) throw new Error('Missing board')
    await board.dispatchEvent('wheel', { deltaY: 10, deltaX: 8, clientX: 200, clientY: 150 })
    await board.dispatchEvent('wheel', { deltaY: 60, clientX: 200, clientY: 150 })
    const after = await board.boundingBox()
    if (!after) throw new Error('Missing board')
    expect(after.width).toBeCloseTo(before.width)
    expect(after.x).toBeCloseTo(before.x - 8)
    expect(after.y).toBeCloseTo(before.y - 70)
    await board.dispatchEvent('wheel', { deltaY: -20, ctrlKey: true, clientX: 200, clientY: 150 })
    await expect.poll(async () => (await board.boundingBox())?.width).toBeGreaterThan(before.width)
})
