import { expect, test } from '@playwright/test'

test('workspace works without a game and ignores railway theme variables', async ({ page }) => {
    await page.goto('/session-test.html')
    await page.evaluate(async () => {
        const { mountWorkspace } = await import(new URL('/src/lib/components/tests/workspace.fixture.ts', location.href).href)
        mountWorkspace()
    })
    const editor = page.getByRole('tab', { name: 'Editor', exact: true })
    await expect(editor).toHaveCSS('color', 'rgb(55, 65, 81)')
    await page.getByRole('textbox', { name: 'editor draft' }).fill('preserved')
    await page.getByRole('button', { name: 'Pane options for Example pane 1' }).click()
    await expect(page.locator('.widget-menu:popover-open')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
    await expect(page.getByRole('button', { name: 'Close editor tab' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Split pane 1 vertically' }).click()
    await editor.dragTo(page.getByText('Drag a tab here', { exact: true }))
    await expect(page.getByRole('textbox', { name: 'editor draft' })).toHaveValue('preserved')
    const divider = page.getByRole('separator', { name: 'Resize vertical split' })
    await divider.focus()
    await page.keyboard.press('ArrowRight')
    await expect(divider).toHaveAttribute('aria-valuenow', '52')
    await expect(page.getByLabel('Saved layout')).toContainText('"cols",52')
    await page.getByRole('button', { name: 'Pane options for Example pane 2' }).click()
    await page.getByRole('button', { name: 'Notes', exact: true }).click()
    await expect(page.getByRole('tab', { name: 'Notes', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Delete pane 2', exact: true }).click()
    await expect(page.getByRole('tablist')).toHaveCount(1)
    await editor.click()
    await expect(page.getByRole('textbox', { name: 'editor draft' })).toHaveValue('preserved')
})
