export enum ActionType {
    ChooseStartCity = 'ChooseStartCity',
    RevealStartCities = 'RevealStartCities',
    BeginRound = 'BeginRound',
    PlaceBid = 'PlaceBid',
    PassBid = 'PassBid',
    ResolveAuction = 'ResolveAuction',
    MoveGuildMaster = 'MoveGuildMaster',
    Sail = 'Sail',
    BuildOffice = 'BuildOffice',
    BuyRouteMarkers = 'BuyRouteMarkers',
    TradeGoods = 'TradeGoods',
    ChangeRoute = 'ChangeRoute',
    ClaimRaidMarker = 'ClaimRaidMarker',
    ClaimBonusChit = 'ClaimBonusChit',
    ExchangeGoodForMarker = 'ExchangeGoodForMarker',
    ExchangeMarkerForGood = 'ExchangeMarkerForGood',
    RaidCity = 'RaidCity',
    RaidCog = 'RaidCog',
    DivideSpoils = 'DivideSpoils',
    ChooseSpoils = 'ChooseSpoils',
    ExpelRaider = 'ExpelRaider',
    EndTurn = 'EndTurn'
}
